### ISSUE TITLE
[REPO] Some Issues re This Github Repo

### ISSUE THREAD

**Issue by abebeos** [urllib3/urllib3#3282] opened 2024-01-17 09:54 UTC
- [x] update milestone https://github.com/urllib3/urllib3/milestone/9
- [x] add (screaming red) `bug` and `feature` labels to the issues
  - [ ] autoassign them for new issues
- [ ] Consider moving `feature` requests to a discussion forum
- process old issues: 
  - [ ] https://github.com/urllib3/urllib3/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc
  - [ ] https://github.com/urllib3/urllib3/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc
- process old PRs:
  - [ ] https://github.com/urllib3/urllib3/pulls?q=is%3Apr+is%3Aopen+sort%3Acreated-asc

EDIT:
### http2

- [ ] Consider adding a https://github.com/urllib3/urllib3/projects for
- https://github.com/urllib3/urllib3/issues/3000

EDIT2:
- [ ] use standard github special label `good first issue` instead of `Contributor Friendly`
  - thus broader queries for this label work
- [ ] use standard github special label `help wanted`
  - gets them listed in the repo overview (like `123 (5 issues need help)`)
- [ ] use label `has bounty` for PRs that affect issues with a bounty
  - Thus reviewers can prioritize those (=> happy bounty-workers)

**Comment by sigmavirus24** [comment] 2024-01-17 11:27
Why are these issues in your opinion?

All of these are a matter of opinion, not fact. Issues are not a bug until they're reproduced. Issues are sometimes spam, other times they are requests for help, other times they're people listing opinions as indisputable work that maintainers are ostensibly required to do (hint: they're not).

**Comment by abebeos** [comment] 2024-01-17 11:37
I am really(!) not in the mood to discuss standard-procedures. Let's await what the lead maintainer has to say.

**Comment by sethmlarson** [comment] 2024-01-17 15:12
* I like the idea for an HTTP/2 project, I'll create that.
* The 2.x milestone isn't as useful anymore since now we're just on the normal development train. I'll ponder closing it out.
* Agreed we have a lot of stale issues and PRs, I believe many of them are valuable and require some time to figure out what to do with them. A few though likely aren't relevant anymore.
* I created a few new labels for "Feature Request" and "Confirmed Bug". We can likely auto-assign Feature Request from our GitHub template.

**Comment by abebeos** [comment] 2024-01-17 15:20
> * Confirmed Bug".

Possibly better to stick to the standard `bug` label, and add an additional `confirmed` label.

**Comment by abebeos** [comment] 2024-01-17 15:21
> * We can likely auto-assign Feature Request from our GitHub template.

Yes

**Comment by abebeos** [comment] 2024-01-17 16:28
@sethmlarson , updated a bit (as a general rule, stick to the quasi-standards whenever possible)

**Comment by sethmlarson** [comment] 2024-01-19 04:42
- Created an HTTP/2 milestone
- I don't necessarily want to use "good first issue", because most of those issues aren't good for someones very first PR (which is how GitHub and other services tend to frame them). I like our label.
- Help wanted is redundant, we want help on almost every issue.
- Bounties can already be filtered for, we have a URL/saved query for it in our contributing guide iirc
- The backlog of issues will require someone looking through it and recommending what to do, I don't think we should have an issue open for that.

I think that covers everything, going to close this issue.

**Closed by sethmlarson** 2024-01-19 04:42 UTC

**Comment by abebeos** [comment] 2024-01-19 05:27
> going to close this issue.

- hey @sethmlarson , don't close issues so fast, this one is still actionable.
- stick to the quasi-standards whenever possible (especially on tool-platforms like github, where users got used to the  quasi-standard-procedures (even if they're flawed ones)

=> at a minimum, use the standard `bug` label (red, no emoji)
