### ISSUE TITLE
OverflowError: signed integer is greater than maximum

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2513] opened 2022-01-02 17:41 UTC
Both of the below calls result in an `OverflowError` being raised because the `Content-Length` is longer than 3GB. OpenSSL only supports reading (2**31)-1 bytes in a single read call.

```python
url = "https://dailymed-data.nlm.nih.gov/public-release-files/dm_spl_release_human_rx_part1.zip"

resp = http.request("GET", url)
resp.data

resp = http.request("GET", url, preload_content=False)
list(resp.stream(None))
```

```
Traceback (most recent call last):
  File "/home/sethmlarson/urllib3/testme.py", line 5, in <module>
    resp = http.request("GET", "https://dailymed-data.nlm.nih.gov/public-release-files/dm_spl_release_human_rx_part1.zip")
  File "/home/sethmlarson/urllib3/src/urllib3/__init__.py", line 112, in request
    return _DEFAULT_POOL.request(
  File "/home/sethmlarson/urllib3/src/urllib3/_request_methods.py", line 109, in request
    return self.request_encode_url(
  File "/home/sethmlarson/urllib3/src/urllib3/_request_methods.py", line 142, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/sethmlarson/urllib3/src/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/sethmlarson/urllib3/src/urllib3/connectionpool.py", line 744, in urlopen
    response = self.ResponseCls.from_httplib(
  File "/home/sethmlarson/urllib3/src/urllib3/response.py", line 748, in from_httplib
    resp = ResponseCls(
  File "/home/sethmlarson/urllib3/src/urllib3/response.py", line 467, in __init__
    self._body = self.read(decode_content=decode_content)
  File "/home/sethmlarson/urllib3/src/urllib3/response.py", line 664, in read
    data = self._fp.read() if not fp_closed else b""
  File "/home/sethmlarson/.pyenv/versions/3.8.6/lib/python3.8/http/client.py", line 471, in read
    s = self._safe_read(self.length)
  File "/home/sethmlarson/.pyenv/versions/3.8.6/lib/python3.8/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/home/sethmlarson/.pyenv/versions/3.8.6/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/sethmlarson/.pyenv/versions/3.8.6/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/sethmlarson/.pyenv/versions/3.8.6/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
OverflowError: signed integer is greater than maximum
```

The fix would likely need to go into `urllib3.response.HTTPResponse` to limit the amount of data requested in a single call to `http.client.HTTPResponse.read(amt)`.

Originally reported in https://github.com/psf/requests/issues/5969

### Minimum requirements

:dollar: **You can get paid to complete this issue! [Please read the docs for more information](https://urllib3.readthedocs.io/en/latest/contributing.html#getting-paid-for-your-contributions).**

- [ ] Ensure that any call to `urllib3.response.HTTPResponse.read(...)` never results in a call to `.read(n)` with a value greater than `n=(2**31)-1`. Behavior should not change for users, you should buffer bytes into a `bytearray` and then return the stitched together data when necessary.
- [ ] Test cases for streaming chunk sizes, `.read(2**31)`, `.read(None)`, `.read()`, `preload_content=True`
- [ ] Merge fix into both `main` and `1.26.x` branches

**Comment by elijahbenizzy** [comment] 2022-01-18 19:32
Thanks for bringing this up! Excited to see a solution, we've been hitting this as well. In the meanwhile does anyone happen to have any reasonable workarounds?

**Comment by sethmlarson** [comment] 2022-01-18 21:10
The best solution is to stream the response data instead of loading all at once. You'll likely want to do this anyways (even with the fix here) as loading 3GB into memory all at once isn't likely to be performant.

**Comment by rlamy** [comment] 2022-06-09 15:19
I've looked a bit into the issue and IMHO changing the logic of `HTTPResponse.read()` would be wrong. 

First, it's currently possible to call `.read()` with `amt` larger than `2**31` - if you're using HTTP instead of HTTPS. For instance, if you replace the URL in the OP with `url = "http://speed.hetzner.de/10GB.bin"`, things seem to work as intended. And `HTTPResponse.read()` has no way of guessing what the underlying connection supports.

I guess that the issue here is mainly due to the obscure error message. From my (limited) understanding of the respective scopes of urllib3 and requests, I'd say that `urllib3.request('GET', HUGE_FILE)` is user error, unlike `requests.get(HUGE_FILE)` which should just work. Additionally, the behaviour of `.stream(None)` is another source of confusion, since it just wraps the result of `.read()` in a one-element iterator instead of acting like `.stream()` as I would have expected.

**Comment by illia-v** [comment] 2022-06-10 16:59
When CPython is used, the error should only happen since 3.8.0a4 (https://github.com/python/cpython/issues/80231, https://github.com/python/cpython/commit/d6bf6f2d0c83f0c64ce86e7b9340278627798090), it was fixed in 3.9.7 (https://github.com/python/cpython/issues/87019, https://github.com/python/cpython/commit/153365d864c411f6fb523efa752ccb3497d815ca), the fix was not backported to 3.8.

In the course of https://github.com/python/cpython/issues/87020, [one more regression](https://twitter.com/geofft/status/1417167982665551877) was introduced in 3.10.0b1 (https://github.com/python/cpython/commit/89d1550d14ba689af12eeb726e4ff8ce73cee7e1) and fixed in 3.10.0rc1 (https://github.com/python/cpython/commit/5ec275758dbc307e9838e7038bfc3b5390950ea7).

**Comment by illia-v** [comment] 2022-06-10 19:33
> * [ ]  Ensure that any call to `urllib3.response.HTTPResponse.read(...)` never results in a call to `.read(n)` with a value greater than `n=(2**31)-1`. Behavior should not change for users, you should buffer bytes into a `bytearray` and then return the stitched together data when necessary.

Perhaps, it should never result in a call without `n` too because the overflow can still happen when `n` is not provided and a resource is huge.

I tried writing a fix in https://github.com/illia-v/urllib3/commit/2d6cf6c6f2714e5ad6455c1e665af83e9af9293f, but a few existing tests became broken on 3.8 and 3.9.2. `http.client.HTTPResponse.read` seems to behave differently in terms of raising `IncompleteRead` depending on the presence of `n` (`n` is actually called `amt`.)

**Comment by sethmlarson** [comment] 2022-06-11 13:50
@illia-v Hmm! Could you create a PR with your changes so we can see test results? Would be good to understand all the cases where IncompleteRead are raised too.

**Comment by illia-v** [comment] 2022-06-25 17:09
> @illia-v Hmm! Could you create a PR with your changes so we can see test results? Would be good to understand all the cases where IncompleteRead are raised too.

I created #2657. I've made some changes since the comment to keep having `IncompleteRead` raised.

**Closed** 2022-07-19 20:50 UTC
Labels: 💰 Bounty $100
