### ISSUE TITLE
bandcamp 403 with urllib-2.2.x (worked with urllib-1.26.x)

### ISSUE THREAD

**Issue by woffs** [urllib3/urllib3#3439] opened 2024-08-03 22:24 UTC
### Subject

As mentioned in https://github.com/impliedchaos/mopidy-bandcamp/issues/25 mopidy-bandcamp fails under NixOS, getting a 403 response from bandcamp since a few weeks.

### Environment

Describe your environment.
At least, paste here the output of:

```
>>> print("OS", platform.platform())
OS Linux-6.6.43-x86_64-with-glibc2.39
>>> print("Python", platform.python_version())
Python 3.11.9
>>> print(ssl.OPENSSL_VERSION)
OpenSSL 3.0.14 4 Jun 2024
>>> print("urllib3", urllib3.__version__)
urllib3 2.2.1
```

### Expected Behavior
~/git/urllib3 (1.26.19)$ rm -r /tmp/u ; nix run nixpkgs#python3Packages.pip -- install --prefix /tmp/u .
~/git/urllib3 (1.26.19)$ PYTHONPATH=/tmp/u/lib/python3.11/site-packages/ nix run nixpkgs#python3 -- -c 'import urllib3;print(urllib3.PoolManager().request("GET","https://bandcamp.com/api/fan/2/collection_summary").status)'
200

### Actual Behavior

~/git/urllib3 (main)$ rm -r /tmp/u ; nix run nixpkgs#python3Packages.pip -- install --prefix /tmp/u .
~/git/urllib3 (main)$ PYTHONPATH=/tmp/u/lib/python3.11/site-packages/ nix run nixpkgs#python3 -- -c 'import urllib3;print(urllib3.request("GET","https://bandcamp.com/api/fan/2/collection_summary").status)'
403

**Comment by woffs** [comment] 2024-08-04 11:10
First "bad commit" is https://github.com/urllib3/urllib3/commit/841a7271750b2694589f292e3f395541319a2a44 according to git-bisect, so it's apparently a TLS-related change which triggers some interesting behaviour at the bandcamp.com server (client-certificate handling with tls1.3? I do not know). And it's reproducible on NixOS, but not on Debian - so maybe the fix is to find in the NixOS TLS system settings?

**Comment by pquentin** [comment] 2024-08-13 18:28
Are you able to perform a packet capture (using Wireshark or tcpdump) with urllib3 2.x on NixOS and Debian to see what the difference is? It could be a variant of https://quentin.pradet.me/blog/fixing-sslv3_alert_handshake_failure-with-urllib3-20.html where the server issues a 403 if a configuration was chosen that it does not like? Very hard to tell for now.

**Comment by 7x11x13** [comment] 2024-08-14 00:25
Able to reproduce on Mac as well:
```
$ python3 -m venv urllib_venv
$ urllib_venv/bin/pip3 install urllib3
$ urllib_venv/bin/python3 -c "import urllib3;print(urllib3.request('GET','https://bandcamp.com').status)"
403
```

```
>>> print("OS", platform.platform())
OS macOS-14.4-arm64-arm-64bit
>>> print("Python", platform.python_version())
Python 3.11.5
>>> print(ssl.OPENSSL_VERSION)
OpenSSL 3.3.1 4 Jun 2024
>>> print("urllib3", urllib3.__version__)
urllib3 2.2.2
```

**Comment by pquentin** [comment] 2024-08-23 06:26
I'm also reproducing on macOS, thanks. While it seems TLS related, I don't understand why Bandcamp would accept the TLS connection and then immediately close it using HTTP. Still, since @woffs suggested https://github.com/urllib3/urllib3/commit/841a7271750b2694589f292e3f395541319a2a44 is the culprit, I looked at the ciphers sent by urllib3 and chosen by the server to see if there was a difference.

## urllib3 main branch

We mention accepting the following cipher suites over TLS 1.3.

```
Cipher Suites (18 suites)
    Cipher Suite: TLS_AES_256_GCM_SHA384 (0x1302)
    Cipher Suite: TLS_CHACHA20_POLY1305_SHA256 (0x1303)
    Cipher Suite: TLS_AES_128_GCM_SHA256 (0x1301)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)
    Cipher Suite: TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (0xc024)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x009f)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x009e)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (0x006b)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (0x0067)
    Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
```

The servers chooses TLS_AES_128_GCM_SHA256. Great choice.

### urllib3 1.26.x

We accept the following cipher suites:

Cipher Suites (37 suites)
    Cipher Suite: TLS_AES_256_GCM_SHA384 (0x1302)
    Cipher Suite: TLS_CHACHA20_POLY1305_SHA256 (0x1303)
    Cipher Suite: TLS_AES_128_GCM_SHA256 (0x1301)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)
    Cipher Suite: TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x009f)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x009e)
    Cipher Suite: TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xccaa)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CCM (0xc0ad)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CCM (0xc0ac)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (0xc024)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CCM (0xc09f)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CCM (0xc09e)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (0x006b)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (0x0067)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x0039)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x0033)
    Cipher Suite: TLS_RSA_WITH_AES_256_GCM_SHA384 (0x009d)
    Cipher Suite: TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c)
    Cipher Suite: TLS_RSA_WITH_AES_256_CCM (0xc09d)
    Cipher Suite: TLS_RSA_WITH_AES_128_CCM (0xc09c)
    Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA256 (0x003d)
    Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA256 (0x003c)
    Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
    Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
    Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)

And bandcamp.com *still* chooses Cipher Suite: TLS_AES_128_GCM_SHA256. So something else is at play here.

**Comment by pquentin** [comment] 2024-08-23 06:43
OK, so I can also confirm that https://github.com/urllib3/urllib3/commit/841a7271750b2694589f292e3f395541319a2a44 is the culprit. Since the only difference is the ciphers we sent, well, I tried sending the exact same ciphers:

```python
from urllib3 import PoolManager
from urllib3.util import create_urllib3_context

ctx = create_urllib3_context()
ctx.load_default_certs()

DEFAULT_CIPHERS = ":".join(
    [
        "ECDHE+AESGCM",
        "ECDHE+CHACHA20",
        "DHE+AESGCM",
        "DHE+CHACHA20",
        "ECDH+AESGCM",
        "DH+AESGCM",
        "ECDH+AES",
        "DH+AES",
        "RSA+AESGCM",
        "RSA+AES",
        "!aNULL",
        "!eNULL",
        "!MD5",
        "!DSS",
        "!AESCCM",
    ]
)
ctx.set_ciphers(DEFAULT_CIPHERS)

with PoolManager(ssl_context=ctx) as pool:
    r = pool.request("GET", "https://bandcamp.com")
    print(r.status)
```

And... it worked! This makes no sense to me. Apparently bandcamp.com really wants to see those other cipher suites, even it's not choosing them. But this is not a bug in urllib3, so I'll go ahead and close it.

Please let me know if you have other concerns.

**Closed by pquentin** 2024-08-23 06:43 UTC

**Comment by sigmavirus24** [comment] 2024-08-23 11:06
I'd guess that this is some kind of CDN/WAF that is in between us and Bandcamp. I'm guessing that it believes that this is an indicator of malicious/automated behaviour (and they're not entirely wrong). Unfortunately this seems to be a consistent problem with WAFs trying to detect Python HTTP clients to block them.
