### ISSUE TITLE
SystemExit in Flask app

### ISSUE THREAD

**Issue by musq** [urllib3/urllib3#2965] opened 2023-04-17 05:40 UTC
### Subject

My Flask app raises `SystemExit` occasionally, and I'm not able to understand why. Also this error happens at exactly `120s` from when the API call is made using `requests`.

### Environment

```
OS: Linux-4.14.246-187.474.amzn2.x86_64-x86_64-with-glibc2.31
Python: 3.10.11

boto3: 1.26.52
cachetools: 5.2.1
ddtrace: 1.7.2
flask: 2.2.2
gunicorn: 20.1.0
requests: 2.28.1
six: 1.16.0
urllib3: 1.26.14
```

### Steps to Reproduce

I haven't yet been able to find a way to reproduce this issue.

### Expected Behavior

`SystemExit` shouldn't happen, and Flask app should continue to behave normally.

### Actual Behavior

Tracebacks of 3 different instances of this issue:

```
builtins.SystemExit: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/wsgi/wsgi.py", line 131, in __call__
    result = self.app(environ, intercept_start_response)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/flask/helpers.py", line 27, in wrapper
    return func(pin, wrapped, instance, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/flask/patch.py", line 562, in _traced_request
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/flask/wrappers.py", line 25, in trace_func
    return wrapped(*args, **kwargs)
  File "/app/discover_job_search/utils/schema.py", line 44, in new_func
    return f(*args, **kwargs)
  File "/app/discover_job_search/api/jobs.py", line 136, in search_jobs
    ) = get_job_search_service().search_jobs_in_google(
  File "/app/discover_job_search/domain/services/__init__.py", line 417, in search_jobs_in_google
    designation_vs_attribute = self.engage_repo.get_entity_attribue_designation(
  File "/usr/local/lib/python3.10/site-packages/cachetools/__init__.py", line 641, in wrapper
    v = func(*args, **kwargs)
  File "/app/discover_job_search/repo/exapi/engage.py", line 126, in get_entity_attribue_designation
    response = engage_api_session.get(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/requests/connection.py", line 97, in _wrap_send
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/app/discover_job_search/repo/exapi/sessions.py", line 29, in send
    return super().send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
SystemExit: 1
```

```
builtins.SystemExit: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/requests/connection.py", line 97, in _wrap_send
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
```

```
builtins.SystemExit: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/wsgi/wsgi.py", line 131, in __call__
    result = self.app(environ, intercept_start_response)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/flask/helpers.py", line 27, in wrapper
    return func(pin, wrapped, instance, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/flask/patch.py", line 562, in _traced_request
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/flask/wrappers.py", line 25, in trace_func
    return wrapped(*args, **kwargs)
  File "/app/discover_job_search/utils/schema.py", line 44, in new_func
    return f(*args, **kwargs)
  File "/app/discover_job_search/api/jobs.py", line 136, in search_jobs
    ) = get_job_search_service().search_jobs_in_google(
  File "/app/discover_job_search/domain/services/__init__.py", line 156, in search_jobs_in_google
    candidate = self._candidate_repo.get(agency_id, agency_candidate_id)
  File "/app/discover_job_search/repo/exapi/candidate.py", line 46, in get
    response = requests.get(
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/requests/connection.py", line 97, in _wrap_send
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
SystemExit: 1
```

**Comment by pquentin** [comment] 2023-04-17 06:36
The actual exception is `SystemExit: 1` which is raised by gunicorn apparently:

>  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
>    sys.exit(1)

According to https://stackoverflow.com/questions/52993280/why-is-gunicorn-calling-sys-exit1 the issue is that your requests are taking too long for gunicorn's taste. In any case, this is not an urllib3 issue, so I'll have to close this issue.

Thanks!

**Closed by pquentin** 2023-04-17 06:36 UTC

**Comment by musq** [comment] 2023-04-17 09:04
Thanks @pquentin! I looked again and what still doesn't make sense to me is that:

I've enabled Connect and Read Timeouts to <60s for my API calls. So why does urllib3 not raise Connect/Read Timeout at 60s and why does the API call remain alive till 120s and then Gunicorn decides to kill the worker?

**Comment by pquentin** [comment] 2023-04-17 10:08
I don't know, sorry, but feel free to reopen when you can reproduce this with urllib3.

**Comment by sigmavirus24** [comment] 2023-04-17 10:27
> Thanks @pquentin! I looked again and what still doesn't make sense to me is that:
> 
> I've enabled Connect and Read Timeouts to <60s for my API calls. So why does urllib3 not raise Connect/Read Timeout at 60s and why does the API call remain alive till 120s and then Gunicorn decides to kill the worker?

Connect and read are two separate timers. If you set each to 60 then it won't timeout before 120s at worst. It could take 59.99s to connect and then fail to read and since urllib3 can only be so exact, the read timeout would hit at say 60.5s so you're then at 120.49s

**Comment by musq** [comment] 2023-04-18 11:20
You guys are awesome! Thanks for your hints. After digging some more, I was able to understand this mystery.

In one case, I had forgot to setup Timeouts. So, I'm doing it now.

In the other case:
1. My `requests` session object calls an API
2. Connection gets made within the specified ConnectTimeout of `6.05s`
3. Then it waits for the first byte in response. This response is never received within the specified ReadTimeout of `61s`
4. So, my `requests` session object issues a retry, and the whole dance repeats
5. As a result, this time gunicorn's timer reaches `120s` before any response is received.
6. And Gunicorn kills the worker with `SystemExit`
