### ISSUE TITLE
Segfault in ssl_.ssl_wrap_socket

### ISSUE THREAD

**Issue by sidekick-eimantas** [urllib3/urllib3#3155] opened 2023-10-10 18:44 UTC
### Subject

Python is segfaulting when trying to open a connection to AWS S3.

### Environment

OS Linux-4.14.255-318-256.530.amzn2.x86_64-x86_64-with-glibc2.36
Python 3.10.12
OpenSSL 3.0.9 30 May 2023
urllib3 2.0.6

The service is running on AWS Lambda, in a Docker x86 container.

### Steps to Reproduce

Unfortunately, wont be of much help here. I am unable to reproduce it on my local machine and therefore cannot reduce the code sample.

Its an asynchronous FastAPI + Uvicorn application. Soon after it starts up, it's invoking multiple AWS S3 API calls using `boto3` with `asyncio.to_thread`. The calls are parallelized using `asyncio.gather`. Those API calls are the first outbound network connections that the service makes. The service segfaults as it's attempting to establish a connection.

Interestingly enough, adding the following code to execute after the server starts, before the AWS S3 API calls are made, "fixes" this problem:
```py
async with httpx.AsyncClient() as client:
        await client.get("https://google.com")
```

### Expected Behavior

No segfault

### Actual Behavior

```
2023-10-10T18:23:23.949Z	Deleting object events-index/received-at/2023/10/10/18/23/23/06525969-bf1b-7665-8000-3ceb4260cb04
2023-10-10T18:23:24.060Z	Fatal Python error: Segmentation fault
2023-10-10T18:23:24.060Z	Thread 0x00007f77d0ea06c0 (most recent call first):
2023-10-10T18:23:24.060Z	File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 444 in ssl_wrap_socket
2023-10-10T18:23:24.060Z	File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 783 in _ssl_wrap_socket_and_match_hostname
2023-10-10T18:23:24.060Z	File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 642 in connect
2023-10-10T18:23:24.060Z	File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092 in _validate_conn
2023-10-10T18:23:24.060Z	File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467 in _make_request
2023-10-10T18:23:24.061Z	File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790 in urlopen
2023-10-10T18:23:24.061Z	File "/usr/local/lib/python3.10/site-packages/botocore/httpsession.py", line 465 in send
2023-10-10T18:23:24.061Z	File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 377 in _send
2023-10-10T18:23:24.061Z	File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 281 in _do_get_response
2023-10-10T18:23:24.061Z	File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 241 in _get_response
2023-10-10T18:23:24.061Z	File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 199 in _send_request
2023-10-10T18:23:24.061Z	File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 119 in make_request
2023-10-10T18:23:24.061Z	File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 986 in _make_request
2023-10-10T18:23:24.061Z	File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 963 in _make_api_call
2023-10-10T18:23:24.061Z	File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 535 in _api_call
2023-10-10T18:23:24.062Z	File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58 in run
2023-10-10T18:23:24.062Z	File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 83 in _worker
2023-10-10T18:23:24.062Z	File "/usr/local/lib/python3.10/threading.py", line 953 in run
2023-10-10T18:23:24.062Z	File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
2023-10-10T18:23:24.062Z	File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap
2023-10-10T18:23:24.062Z	Current thread 0x00007f77d16a16c0 (most recent call first):
2023-10-10T18:23:24.062Z	File "/usr/local/lib/python3.10/ssl.py", line 1342 in do_handshake
2023-10-10T18:23:24.062Z	File "/usr/local/lib/python3.10/ssl.py", line 1071 in _create
2023-10-10T18:23:24.062Z	File "/usr/local/lib/python3.10/ssl.py", line 513 in wrap_socket
2023-10-10T18:23:24.062Z	File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 513 in _ssl_wrap_socket_impl
2023-10-10T18:23:24.062Z	File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 469 in ssl_wrap_socket
2023-10-10T18:23:24.063Z	File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 783 in _ssl_wrap_socket_and_match_hostname
2023-10-10T18:23:24.063Z	File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 642 in connect
2023-10-10T18:23:24.063Z	File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092 in _validate_conn
2023-10-10T18:23:24.063Z	File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467 in _make_request
2023-10-10T18:23:24.063Z	File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790 in urlopen
2023-10-10T18:23:24.063Z	File "/usr/local/lib/python3.10/site-packages/botocore/httpsession.py", line 465 in send
2023-10-10T18:23:24.063Z	File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 377 in _send
2023-10-10T18:23:24.063Z	File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 281 in _do_get_response
2023-10-10T18:23:24.063Z	File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 241 in _get_response
2023-10-10T18:23:24.063Z	File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 199 in _send_request
2023-10-10T18:23:24.064Z	File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 119 in make_request
2023-10-10T18:23:24.064Z	File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 986 in _make_request
2023-10-10T18:23:24.064Z	File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 963 in _make_api_call
2023-10-10T18:23:24.064Z	File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 535 in _api_call
2023-10-10T18:23:24.064Z	File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58 in run
2023-10-10T18:23:24.072Z	File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 83 in _worker
2023-10-10T18:23:24.073Z	File "/usr/local/lib/python3.10/threading.py", line 953 in run
2023-10-10T18:23:24.073Z	File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
2023-10-10T18:23:24.073Z	File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap
2023-10-10T18:23:24.073Z	Thread 0x00007f77d7e51b80 (most recent call first):
2023-10-10T18:23:24.073Z	File "/usr/local/lib/python3.10/asyncio/runners.py", line 44 in run
2023-10-10T18:23:24.073Z	File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 61 in run
2023-10-10T18:23:24.073Z	File "/usr/local/lib/python3.10/site-packages/event_gateway/cli/commands/_run_ingest_api.py", line 31 in run_ingest_api
2023-10-10T18:23:24.073Z	File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 683 in wrapper
2023-10-10T18:23:24.073Z	File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783 in invoke
2023-10-10T18:23:24.073Z	File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434 in invoke
2023-10-10T18:23:24.074Z	File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688 in invoke
2023-10-10T18:23:24.074Z	File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 216 in _main
2023-10-10T18:23:24.074Z	File "/usr/local/lib/python3.10/site-packages/typer/core.py", line 778 in main
2023-10-10T18:23:24.074Z	File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157 in __call__
2023-10-10T18:23:24.074Z	File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 311 in __call__
2023-10-10T18:23:24.074Z	File "/usr/local/lib/python3.10/site-packages/event_gateway/__main__.py", line 5 in main
2023-10-10T18:23:24.074Z	File "/usr/local/bin/event-gateway", line 8 in <module>
2023-10-10T18:23:24.075Z	Extension modules: psutil._psutil_linux, psutil._psutil_posix, setproctitle._setproctitle, _cffi_backend, uvloop.loop, httptools.parser.parser, httptools.parser.url_parser, websockets.speedups (total: 8)

```

I'm happy to help debug this further and give access to an AWS sandbox running this service if that helps.

**Comment by pquentin** [comment] 2023-10-11 12:37
I checked and uvicorn does not appear to do anything specific ssl patching. @Kludex can you please confirm?

Anyway, what the error is telling us is that you have multiple threads reusing the same SSLContext object, doing two things at the same time with `asyncio.to_thread` and `asyncio.gather`:

 * Thread 0x00007f77d0ea06c0 is calling [SSL_CTX_load_verify_locations](https://www.openssl.org/docs/man3.0/man3/SSL_CTX_load_verify_locations.html) with the GIL disabled: https://github.com/python/cpython/blob/f83fa0b9eb1c11a4ef53275d77c603b97335eb23/Modules/_ssl.c#L4164-L4166.  This is an IO-heavy operation that 
 * Thread 0x00007f77d16a16c0 is calling [SSL_do_handshake](https://www.openssl.org/docs/man3.0/man3/SSL_do_handshake.html), also with the GIL disabled: https://github.com/python/cpython/blob/f83fa0b9eb1c11a4ef53275d77c603b97335eb23/Modules/_ssl.c#L991-L994

My theory is that a bug in OpenSSL 3.0 means that those two operations are not thread-safe and cannot be executed together. The fact that making a single-threaded request solves the issue gives credit to that theory, even if I suppose it's not using the same SSLContext. Maybe there's some caching involved meaning that the next calls are super fast?

The other thing I don't understand is that since Thread 0x00007f77d16a16c0 was already doing the handshake, surely it has already called SSL_CTX_load_verify_locations?


@sidekick-eimantas How easy is it to extract the call invoking multiple AWS S3 API calls at startup? My hunch is that just that should fail the same way, eliminating Uvicorn and FastAPI altogether.

**Comment by pquentin** [comment] 2023-10-12 03:02
Thanks! In this case interestingly all threads are in `do_handshake`, partially invalidating my previous theory. But having such a short reproducer is nice. The next step will be to remove boto3, requests, urllib3 and even http.client out of the picture I suspect.

How much memory do you allocate to your Lambda? It directly affects the vCPU-seconds available:

> You can increase or decrease the memory and CPU power allocated to your function using the Memory (MB) setting. To configure the memory for your function, set a value between 128 MB and 10,240 MB in 1-MB increments. At 1,769 MB, a function has the equivalent of one vCPU (one vCPU-second of credits per second).

**Comment by sethmlarson** [comment] 2023-11-13 15:21
@sidekick-eimantas Has there been any progress on this front? Currently I'm not thinking this is an issue with urllib3 directly, instead with either CPython or OpenSSL and that an issue should be opened on one of those projects once we determine where it lays.

**Comment by sethmlarson** [comment] 2023-11-20 05:45
Going to close this as no progress has been made and I think this isn't an issue in urllib3.

**Closed by sethmlarson** 2023-11-20 05:45 UTC
