### ISSUE TITLE
what is the official relation between urllib3 and upstream python?

### ISSUE THREAD

**Issue by joernhees** [urllib3/urllib3#1065] opened 2016-12-06 10:33 UTC
Given that urllib and urllib2 are part of the core-libs, it doesn't seem unrealistic that at some point a urllib3 will be part of the core-libs.

Please prominently point out what your relation to upstream python is.

**Comment by Lukasa** [comment] 2016-12-06 10:34
What kind of message would help with this problem, and where would we have needed to put it to help you?

**Comment by Lukasa** [comment] 2016-12-06 10:39
I should note that the odds of a urllib3 ever appearing in the standard library are very slim, in part because the basic premise of urllib is no longer well regarded by the CPython maintainers, and in part because of the prominence of this library.

**Comment by joernhees** [comment] 2016-12-06 10:49
Where? For example as a section on https://urllib3.readthedocs.io/en/latest/

What kind? Uhm, plain text... ;) Jokes aside... as a maintainer of some python libs myself, i ask myself if basing on urllib3 will cause long term problems due to the obvious elephant in the room.
If you have indications that it won't, cool. Just be open about it.

**Comment by Lukasa** [comment] 2016-12-06 11:31
I guess my question was really more about whether it needed to be a really prominent section. I don't think it does, to be honest, so I'll take a look at the docs and see if there is somewhere sensible to put it.

**Comment by Lukasa** [comment] 2016-12-06 12:57
Hrm. On second thoughts, I'm wondering whether this is really necessary in the documentation. We don't really have very much to say on the topic.

**Comment by sigmavirus24** [comment] 2016-12-06 13:14
> On second thoughts, I'm wondering whether this is really necessary in the documentation. We don't really have very much to say on the topic.

This is my feeling as well. urllib3 has only been considered for standard library inclusion when requests was being considered (and only because it's a dependency of requests). Since that has been firmly ruled out and a portion of urllib3 is provided by the stdlib, I don't see why this would ever be included or considered for inclusion at this point.

I can understand how the naming might be confusing, but the name of third party packages should never be considered indication of whether or not it'll ever join the standard library.

**Comment by haikuginger** [comment] 2016-12-06 14:08
> the name of third party packages should never be considered indication of whether or not it'll ever join the standard library.

I agree with @sigmavirus24 and @Lukasa. I think a section saying "urllib3 is not now and never will be part of the standard library" would likely be more confusing than the status quo; it could validate the perception that urllib3 is a newer version of urllib/urllib2 rather than a completely separate project.

**Comment by joernhees** [comment] 2016-12-06 14:48
Well, my external feedback is: a name like urllib3 comes with certain implications...

For me it went like this:
- urllib and urllib2... aaaah, finally requests... THANKS
- then a couple of years later, urllib3?
- oh cool, seems requests and pip now use that
- cool, they're probably gonna put some stuff back upstream, nice
- wait, it's in a "shazow" namespace on github? weird
- hmm, nothing in their docs says anything about their plan?! weird
- if that's not their plan, what will they do if urllib3 ever comes out?
- also isn't that just core lib name hijacking?

Don't get me wrong... i like your project, but please consider removing a big part of that bad feeling i get by just clarifying it explicitly. For example with something like this (please correct if wrong)...

> ## Relation to upstream Python, urllib and urllib2
> urllib3 is a community effort to offer features missing from Python's core urllib and urllib2. Adding these features to urllib and urllib2 would be a lengthy process and introduce many backwards incompatibilities. Being a community driven library allows us to avoid this and update and extend urllib3 as necessary. Hence, there are currently no plans to internalize urllib3 into the core libs.

**Comment by sigmavirus24** [comment] 2016-12-06 15:00
> also isn't that just core lib name hijacking?

Not really. As far as we're concerned, anyone living in the present should be thinking `urllib.request` is the standard library version... why is this even `urllib3`? That must be some weird sense of humour.

Also, there are tons of third party packages that base names off core packages that they're improving. Ever hear of `httplib2`? It's fairly common (although not exactly helpful) and none of them ever really intend to inject themselves into the standard library.

**Comment by Lukasa** [comment] 2016-12-06 15:00
Well it should be noted that urllib3 is *not* a logical extension of urllibs 1 and 2.

In particular, those modules were predicated on an architectural style that assumed that it was useful to have a module that focussed on accessing *URLs* generically, rather than protocol-specific implementations. This was a reasonable-enough design decision during their original run, but has not been proven out by history. Ultimately, people don't want to be able to generically open URLs, they want protocol-specific libraries.

This means that urllib3 doesn't aim to improve on urllib or urllib2: it aims to improve on *httplib*. In that sense its name is misleading, but fundamentally the name was intended to be a joke. I don't think @shazow ever really expected we'd get this far.

But fundamentally, I don't know that this *matters*. I can understand that it's a source of confusion, but I don't think this documentation would provide any kind of actionable information for anyone. What decisions or actions would people do differently in possession of this information?

**Comment by SethMichaelLarson** [comment] 2016-12-06 15:03
@Lukasa Exactly what I was thinking with the last paragraph. There's no difference between whether this is clarified or not in what happens with the library or what others do or think about the library. In the end it's a Python library.

**Comment by joernhees** [comment] 2016-12-06 15:14
> Also, there are tons of third party packages that base names off core packages that they're improving. Ever hear of httplib2? It's fairly common (although not exactly helpful) and none of them ever really intend to inject themselves into the standard library.

would be a fair point if there was a httplib and httplib2 already in core...

**Comment by Lukasa** [comment] 2016-12-06 15:15
There *is* a httplib in core. Its name got changed in Python 3, to http.client, but it was originally called httplib.

**Comment by joernhees** [comment] 2016-12-06 15:17
that's why there is an "and" between httplib *and* httplib2

**Comment by joernhees** [comment] 2016-12-06 15:22
ah, now we're at the level of actively trying to not understand?

i guess the maintainer view on this is clear... but maybe consider that you might not be the most unbiased sample group when asking about how confusing / misleading external users might find the name urllib3.

anyhow, i rest my case, as this is becoming too heated.

**Comment by Lukasa** [comment] 2016-12-06 15:24
@joernhees I'm not actively trying not to understand. I did not understand that you were originally trying to suggest that one entry does not form a pattern.

Regardless, right now we've had only one person express any kind of confusion to us in the lifetime of the project. That's an important data point, but does not yet point to any kind of widespread misunderstanding that we need to address. Ultimately, all I'd like to know is what value we give the community and our users by providing documentation like this.

**Comment by shazow** [comment] 2016-12-06 16:11
I can confirm that the name of urllib3 is one of my regrets. :P The joke was: urllib and urllib2 have nothing to do with each other (the designs are vastly different and separate), so urllib3 will also have nothing to do with the other two. lol?

I discussed the inclusion of urllib3 into the stdlib with Guido some 5+ PyCons ago. His feeling at the time was that urllib3 would only be held back due to the stdlib's slow release process. Honestly I'm not convinced that this is a good reason (maybe that's something that Python core should address).

Anyways, I think it's fairly easy to tell whether something is part of the standard library versus not: Do you need to pip install it? Then it's a third-party thing. Can you import it without installing it? Then it's in the standard library.

P.S. urllib3 predates requests. :P

**Comment by kbkaiser** [comment] 2017-02-28 00:10
It should be noted that the current docs for urllib.request says:

"See also: The Requests package is recommended for a higher-level HTTP client interface."

**Comment by parity3** [comment] 2017-12-28 07:39
Simply having this issue public on github goes quite far in explaining away my confusion. Thanks all, and thanks google search!

**Closed** 2018-08-06 18:31 UTC

**Comment by rayluo** [comment] 2018-08-13 20:10
Considering that the latest activity in this issue happened just 7 days ago, I think I'm technically still not too late to join the conversation. :-)

I am one of the happy user of the requests lib and I don't normally even pay attention to urllib3, so its naming would otherwise be irrelevant to me. Yet today I feel a need to study the relationship between Requests/urllib3 and the standard urllib/urllib2. If urllib3 was built on top of standard urllib/urllib2, it would mean my app will automatically have TLS 1.2 support comes with the OpenSSL which is compiled into recent versions of Python.

After reading the lengthy conversation in this issue, I found "urllib3 is a completely independent community project ... from Python's core urllib and urllib2" (and even [the joke](https://github.com/urllib3/urllib3/issues/1065#issuecomment-265191841)), so I know I need to head to a different direction to research whether urllib3 itself comes with adequate OpenSSL support. I am able to find the positive answer [here](https://github.com/urllib3/urllib3/blob/master/src/urllib3/connection.py#L14) and [there](https://urllib3.readthedocs.io/en/latest/user-guide.html#certificate-verification-in-python-2), but still hope that the "urllib3 is a completely independent project ... from urllib and urllib2" would be clearly mentioned in the current readme or readthedocs.

**Comment by mjpieters** [comment] 2018-11-04 14:51
@rayluo: Both `urllib` and `urllib3` depend on `httplib` (Py2) / `http.client` (Py3), which in turn builds on the standard library [`ssl` module](https://docs.python.org/3/library/ssl.html) for TLS support.  `urllib`'s contribution is limited to an `if _has_ssl:` test to pull in the HTTPS support from `http.client`.

So to see if you have TLS support, *focus on `http.client`, not `urllib`.

**Comment by skjerns** [comment] 2020-10-19 09:10
I'm reviving this ancient issue to let you know that it finally resolved my confusion about `client.http` / `urllib` / `urllib2` / `urllib3` / `requests` / `httplib`. 

As someone that started with Python3 and comes along all of these libraries in older code examples this was majorly confusing.

**Comment by mgaitan** [comment] 2024-09-06 19:20
It's 2024, and I found myself wondering why `urllib3` isn't part of the Python stdlib. After going through this discussion, it seems that not documenting the relationship between `urllib3` and the stdlib (especially `http.client`) isn't as trivial as some of the maintainers suggest. 

It would be helpful if this relationship were clearer, given the importance of `urllib3` for many developers.
