### ISSUE TITLE
module 'urllib3.util' has no attribute 'PROTOCOL_TLS'

### ISSUE THREAD

**Issue by wangoloj** [urllib3/urllib3#1908] opened 2020-07-17 06:31 UTC
This is the error i get i don't know why

```
# Map from urllib3 to PyOpenSSL compatible parameter-values.
_openssl_versions = {
    util.PROTOCOL_TLS: OpenSSL.SSL.SSLv23_METHOD,
    ssl.PROTOCOL_TLSv1: OpenSSL.SSL.TLSv1_METHOD,
}
```
There are no much information I can provide again.

**Comment by sethmlarson** [comment] 2020-07-17 12:06
What version of urllib3 do you have installed?

Try `$ pip freeze`

**Comment by wangoloj** [comment] 2020-07-18 05:50
The version is `urllib3==1.25.9`.
It could be a module collision as the error happens when
`from rest_framework import routers ` 
is important But when I comment of that line of code, the error does not happen. Sorry may not be `urllib3` fault.

**Comment by sethmlarson** [comment] 2020-07-18 16:58
Yeah from my reading of `util.py` there's no way to get an AttributeError for PROTOCOL_TLS. I suspect you're right in that this isn't a defect in urllib3.

If you figure out what the problem is would love to hear about it here. :)

Closing this as not an issue.

**Closed by sethmlarson** 2020-07-18 16:58 UTC
