### ISSUE TITLE
Retry backoff_factor offset from second retry incorrectly computed

### ISSUE THREAD

**Issue by Berbe** [urllib3/urllib3#3377] opened 2024-04-07 15:36 UTC
### Subject
[Per the docs](https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry) the `backoff_factor` parameter applies from the second retry onwards.
However, this strategy is merely implemented by skipping the first step, making the `backoff_factor` start with an inflated delay.
```python
{backoff factor} * (2 ** ({number of previous retries}))
```
will hence sequentially take the following values:
```python
{backoff factor} * (2 ** 1)
{backoff factor} * (2 ** 2)
{backoff factor} * (2 ** 3)
[…]
```
Since there is no previous retry, the expected sequence would be:
```python
{backoff factor} * (2 ** 0)
{backoff factor} * (2 ** 1)
{backoff factor} * (2 ** 2)
[…]
```

This is due to the way the first retry is skipped:
```python
if consecutive_errors_len <= 1:
    return 0
```
It would have been better of the `consecutive_errors_len` had been offsetted

### Environment
```
OS Linux-6.1.0-18-amd64-x86_64-with-glibc2.36
Python 3.11.2
OpenSSL 3.0.11 19 Sep 2023
urllib3 2.2.1
```

### Steps to Reproduce
Any use of `Retry` with `backoff_factor`

### Expected Behavior
Backoff factor started from the identity value (ie first retry made with `backoff_factor` duration)

### Actual Behavior
Backoff factor started with a doubled `backoff factor` duration

**Comment by sethmlarson** [comment] 2024-04-09 03:56
This seems like a duplicate of https://github.com/urllib3/urllib3/issues/3375?

**Closed by sethmlarson** 2024-04-09 03:56 UTC

**Comment by Berbe** [comment] 2024-04-09 17:13
> This seems like a duplicate of #3375?

No it is not. Please reopen for evaluation.
