### ISSUE TITLE
Base headers are missing when using connection_from_host method on PoolManager.

### ISSUE THREAD

**Issue by a-feld** [urllib3/urllib3#1807] opened 2020-02-25 22:08 UTC
When using `connection_from_host` on `PoolManager` classes, the base headers are missing from outbound requests.

## Minimal Reproduction

```python
import json
from pprint import pprint

import urllib3

HEADERS = {"Foo": "bar"}

# Foo header is added to PoolManager base headers
http = urllib3.PoolManager(headers=HEADERS)

# Request is made by using the connection_from_host method
conn = http.connection_from_host("httpbin.org", scheme="https")
response = conn.request("GET", "/headers")

# Foo is missing from the sent headers
sent_headers = json.loads(response.data.decode())
pprint(sent_headers)
```

### Output
```
{'headers': {'Accept-Encoding': 'identity',
             'Host': 'httpbin.org',
             'X-Amzn-Trace-Id': '...'}}
```

### Expected
```
{'headers': {'Accept-Encoding': 'identity',
             'Foo': 'bar',
             'Host': 'httpbin.org',
             'X-Amzn-Trace-Id': '...'}}
```

**Comment by a-feld** [comment] 2020-02-25 22:25
I'm unsure whether this is intended behavior or not based on the discussion in #270 .
I have a fix ready to go if this is indeed confirmed to be a bug 😄

**Comment by sethmlarson** [comment] 2020-03-09 01:26
Based on the discussion in that issue I'm going to close this as not a bug, can see how this is confusing behavior though.

Basically the `headers=...` only applies to the instance you're actually calling `urlopen()` on.

**Closed by sethmlarson** 2020-03-09 01:26 UTC
