### ISSUE TITLE
InsecurePlatformWarning is end-user unfriendly

### ISSUE THREAD

**Issue by rbtcollins** [urllib3/urllib3#615] opened 2015-05-09 19:36 UTC
I filed https://github.com/pypa/pip/issues/2681 when pip started throwing IPW's all over the place, and we've had other folk be confused as well.

Now,  I understand the cause and support the intent of exposing insecure situations for users.

However the page linked to is hard to understand for a couple of reasons.

The page as a whole is focused on developers and the history behind security in urllib3, but end users don't need all that context (and the advice for developers, like the InsecureRequestWarning section, is entirely irrelevant to them). Because the link is to a # reference in the page, and one near the end of the page, the actual advice doesn't appear at the top of the users browser screen, but in a narrow section at the bottom (try opening the page in a 4K browser window...). Lastly, _nearly everyone_ that hits this will need the actual advice: https://urllib3.readthedocs.org/en/latest/security.html#openssl-pyopenssl for which they have to chase pointers.

If I may suggest, putting the #insecureplatformwarning reference at the top of the document, and inlining the pyopenssl recipe into it would make this a whole bunch clearer and hopefully make things a lot clearer for users encountering this issue in an application.
##

**Comment by shazow** [comment] 2015-05-09 20:24
Agreed on most counts! Would you be up for making a PR which improves the clarity of our documentation?

My only reluctance is putting #insecureplatformwarning section at the top, as it would break the incremental narrative. Would have to see what it looks like. :)

**Comment by rbtcollins** [comment] 2015-05-09 21:00
Right now my head is all full of pip issue 988 which I've just got over the hump on (see pip pr 2617) - so I'd suggest someone with a little less OMG-brain-overflow happening tackle it for now.

As for the narrative angle - perhaps something like:

intro - this doc covers all angles of security for urllib3 
 end user issues
  platform warning
  openssl
  certificates
 developer issues
  insecurerequestwarning

**Comment by shazow** [comment] 2015-05-09 23:59
Good luck with pip! Make sure to check back here once you're done, good chance this issue will be waiting for you. :)

**Comment by AvdN** [comment] 2015-05-25 20:12
If you are installing pip on Python 2.6.5 usin get_pip.py you get this warning and you cannot proceed. The one "workaround" is inserting  ``urllib3.disable_warnings()`` after importing urllib3, but you cannot put this in the source get_pip.py as this is hidden in an encoded zipped data block.

The other "workaround" is mentioned as: "This would be a great time to enable HTTPS verification: Using Certifi with urllib3.". And the first step mentioned [there](https://urllib3.readthedocs.org/en/latest/security.html#certifi-with-urllib3) is to run ``pip install certifi``

Running ``python -W ignore get-pip.py`` suppresses the warnings but still doesn't get ``pip``.

Using ``easy_install pip`` works (easy_install itself installed from https://bootstrap.pypa.io/ez_setup.py, but results in a ``pip`` that throws this error.

I appreciate concern about security, but to make it impossible to use the tool you recommend for getting the certificates make life unnecessarily hard.

**Comment by shazow** [comment] 2015-05-26 00:44
@AvdN That sounds like a bug with get-pip.py (cc @dstufft). Warnings as they are should not prevent the working of urllib3, it should just print to stderr and continue.

**Comment by sigmavirus24** [comment] 2015-05-26 01:23
@shazow is correct. This sounds like there's a wholly different problem with your system that is unrelated to these warnings.

**Comment by AvdN** [comment] 2015-05-26 05:21
@sigmavirus24  I tried to reproduce this in a way to pinpoint the possible causes and  make it reproducable. This happens on a new Windows 7 install (32 bit). I only replaced IE with FireFox on that machine. Then downloaded Python 2.6.5, installed. Downloaded get_pip.py Any suggestions  what that different problem might be? Should I not have installed FireFox?

**Comment by dstufft** [comment] 2015-05-26 13:05
Did you actually make sure that the workarounds above work?

I think the warning is a red herring. I'm pretty sure that Python 2.6.5 on Windows is just compiled with an OpenSSL that's too old to successfully interact with PyPI. The ``ez_setup`` script works because it falls back to some system level download tools if the Python level does not work. I'm not sure why ``easy_install`` itself works, but looking at the code it appears to fall back to non SSL in some cases and it's probably hitting one of those cases.

**Comment by sigmavirus24** [comment] 2015-05-26 13:12
@AvdN I think it's specifically a problem with 2.6.5. The 2.6 line of Python has been dead for well over a year (if not 2 years already). The last version of 2.6 was 2.6.9. All code that's valid in 2.6 should be valid in 2.7 and 2.7 is still supported (in fact 2.7.10 was released this weekend). You should probably be using a version of 2.7 if not 2.7.10.

**Comment by sethmlarson** [comment] 2020-08-28 21:26
I don't think anything here is relevant anymore. Closing for now.

**Closed by sethmlarson** 2020-08-28 21:26 UTC
