### ISSUE TITLE
Processing connect timeout when host name resolves to multiple IP addresses

### ISSUE THREAD

**Issue by lorien** [urllib3/urllib3#2055] opened 2020-11-13 04:35 UTC
urllib version is recent (1.26.2)

```
import time
import logging

from urllib3.util import Retry, Timeout
from urllib3 import PoolManager


def main(**kwargs):
    pool = PoolManager()
    url = 'https://google.com:81'

    start = time.time()
    try:
        print('connecting')
        res = pool.request(
            'GET',
            url,
            preload_content=False,
            timeout=Timeout(
                total=None,
                connect=1,
                read=3,
            ),
            retries=Retry(
                total=None,
                connect=0,
                read=0,
                other=0,
                redirect=False,
                raise_on_redirect=False,
                respect_retry_after_header=False,
            ),
        )

        print('reading')
        data = res.read(1024 * 1024)
    except Exception as ex:
        logging.error('ERROR: %s' % ex)
    finally:
        elapsed = time.time() - start
        print('Elapsed: %.2f sec' % elapsed)


if __name__ == '__main__':
    main()
```

I got:
```
connecting
Starting new HTTPS connection (1): google.com:81
ERROR: HTTPSConnectionPool(host='google.com', port=81): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fda8d711cc0>, 'Connection to google.com timed out. (connect timeout=1)'))
Elapsed: 6.01 sec
```

Why 6 seconds? It must be 1 second.

For example, how curl works:
```
$ time curl --connect-timeout 1 -m 3 https://google.com:81
curl: (7) Failed to connect to google.com port 81: Connection timed out

real    0m1.010s
user    0m0.007s
sys     0m0.010s

```

UPD: It is only when I run it on my laptop. It works as expected (timeouts in 1 second) when I run it on remote server.
If I replace `https://google.com:81` with `https://209.85.233.101:81` (it is one of google.com IPs) then it works as expected (timeouts in 1 second) on laptop too.

UPD: When I run it with strace on laptop I see this (among other lines):
```
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 3
setsockopt(3, SOL_TCP, TCP_NODELAY, [1], 4) = 0
ioctl(3, FIONBIO, [1])                  = 0
connect(3, {sa_family=AF_INET, sin_port=htons(81), sin_addr=inet_addr("209.85.233.113")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=3, events=POLLOUT|POLLERR}], 1, 1000) = 0 (Timeout)
close(3)                                = 0
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 3
setsockopt(3, SOL_TCP, TCP_NODELAY, [1], 4) = 0
ioctl(3, FIONBIO, [1])                  = 0
connect(3, {sa_family=AF_INET, sin_port=htons(81), sin_addr=inet_addr("209.85.233.102")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=3, events=POLLOUT|POLLERR}], 1, 1000) = 0 (Timeout)
close(3)                                = 0
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 3
setsockopt(3, SOL_TCP, TCP_NODELAY, [1], 4) = 0
ioctl(3, FIONBIO, [1])                  = 0
connect(3, {sa_family=AF_INET, sin_port=htons(81), sin_addr=inet_addr("209.85.233.138")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=3, events=POLLOUT|POLLERR}], 1, 1000) = 0 (Timeout)
close(3)                                = 0
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 3
setsockopt(3, SOL_TCP, TCP_NODELAY, [1], 4) = 0
ioctl(3, FIONBIO, [1])                  = 0
connect(3, {sa_family=AF_INET, sin_port=htons(81), sin_addr=inet_addr("209.85.233.101")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=3, events=POLLOUT|POLLERR}], 1, 1000) = 0 (Timeout)
close(3)                                = 0
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 3
setsockopt(3, SOL_TCP, TCP_NODELAY, [1], 4) = 0
ioctl(3, FIONBIO, [1])                  = 0
connect(3, {sa_family=AF_INET, sin_port=htons(81), sin_addr=inet_addr("209.85.233.139")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=3, events=POLLOUT|POLLERR}], 1, 1000) = 0 (Timeout)
close(3)                                = 0
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 3
setsockopt(3, SOL_TCP, TCP_NODELAY, [1], 4) = 0
ioctl(3, FIONBIO, [1])                  = 0
connect(3, {sa_family=AF_INET, sin_port=htons(81), sin_addr=inet_addr("209.85.233.100")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=3, events=POLLOUT|POLLERR}], 1, 1000) = 0 (Timeout)
close(3)                                = 0
getpid()                                = 30610
```

So, it tries to connect to every IP the google.com resolves to. What is why it takes 6 seconds instead of 1 seconds. On server the google.com resolves to only one IP, what's why the code timeouts in 1 second on server.

**Comment by pquentin** [comment] 2020-11-13 07:16
Thanks for the strace output. In other words, this works as expected! We could mention this as another gotcha in the Timeout docs, I guess.

**Comment by lorien** [comment] 2020-11-13 14:16
> works as expected

Expected by whom? I mean I was not expected it :) For example, curl does not iterate every possible IP. Why does not urllib3 give up after failed connection to first IP (chosen randomly or by order). Is there a standard or RFC or something that motivates such a behaviour?

**Comment by sigmavirus24** [comment] 2020-11-13 18:53
`urllib3` and `requests` walk a fine line of "let's try to be as helpful to users as possible" and some of that means emulating browsers (which do exactly this to the best of my understanding). It's not specified or required by an RFC but it isn't going to change as users rely on it

**Comment by pquentin** [comment] 2020-11-13 19:08
The relevant RFCs here are known as "Happy Eyeballs" and this is what browsers and curl implement. However Happy Eyeballs is like impossible to get right in practice, which is why it's the Hello World of the structured concurrency paradigm. And urllib3 has the added complexity that we can't spawn threads or event loops.

We have an open issue for that: #797 which claims that it's possible in urllib3 but I don't personally understand why. @sethmlarson even attempted to implement it in #1000. But it stalled. So we just try to connect to each address in turn for now.

I think this issue is a duplicate of #797.

**Comment by sigmavirus24** [comment] 2020-11-13 20:00
I wonder if we could use configured Retry's for this

**Comment by xgchena** [comment] 2021-03-18 23:03
The current behavior confused me a lot. Eventually I narrowed it down to [this loop](https://github.com/urllib3/urllib3/blob/ae02471b5d29d07b24abee957244d1db0f5e56fc/src/urllib3/util/connection.py#L59), and git history shows that it was copied [from Python 2.7](https://github.com/certik/python-2.7/blob/c360290c3c9e55fbd79d6ceacdfc7cd4f393c1eb/Lib/socket.py#L553), so this is indeed long-existing. The pain-point is that it makes the "total" connect timeout of an urllib3 request indeterministic, and in certain cases cause unexpectedly long wait.

I think the issue is not a duplicate of https://github.com/urllib3/urllib3/issues/797, because the ask is different. As a user of urllib3, when I set a connect timeout value to a request, I expect it to be the "total" connect timeout, no matter how many IP addresses the host name resolves to, and no matter those IPs are IPv4 or IPv6. 

----

For your reference, here is the issue I met:

* I shared a docker image to customers who run the image in Amazon AWS. The application code in the docker image calls a couple of AWS services using AWS Python SDK API (which in turn uses urllib3).
* The code worked well until a customer tried to use it in a AWS VPC whose outbound traffic was disabled by default, that means, without VPC PrivateLinks to those AWS services, the loop code above could resolve a service endpoint to IPs, but it could not connect to any of them, eventually a request failed by ConnectTimeoutError.
* The timeout error itself is acceptable because it does indicate the VPC configuration issue, the problem was the time-to-failure. The code uses the default 1min timeout value, and max 5 retries, so the "expected" timeout time of a singel service call is 1min*(1+5) = 6min. In the code's main flow, the first two service calls have fallbacks, and the third one can fail the job. So the "expected" time-to-failure is 6min\*3=18min. But the service endpoint is resolved to 3 IP addresses, so the actual time-to-failure was tripled: 54min.
* The timeout/retry settings are general purpose (not just for connections) so I can not alter them. As a workaround, at the verify beginning of the code flow I added a code block which uses 10s timeout and 1 retry to check the connectivity to the AWS services to be called, this way the job can fail fast (currently in 1min) in case of VPC configuration problem.

The behavior can be reproduced locally like this,

* Append some dummy resolutions to hosts file (for example, in macOS case the file is `/private/etc/hosts`),

```
...
1.2.3.4 timeout-test.com
1.2.3.5 timeout-test.com
1.2.3.6 timeout-test.com
```

* Run below code

```
from datetime import datetime

from urllib3 import Retry, Timeout, PoolManager
from urllib3.exceptions import MaxRetryError, ConnectTimeoutError

start_time = datetime.now()
endpoint_url = "https://timeout-test.com"  # a random non-exist host
retries = Retry(connect=0, read=0)
timeout = Timeout(connect=5, read=5)
pool_manager = PoolManager(retries=retries, timeout=timeout)
try:
    pool_manager.request("GET", endpoint_url, redirect=False)
except MaxRetryError as e:
    if isinstance(e.reason, ConnectTimeoutError):
        diff = datetime.now()-start_time
        print(f"Timeout: {diff}s")
```

The result (=5s timeout * 3 IP addresses),

```
Timeout: 0:00:15.013800s
```

**Comment by pierky** [comment] 2022-08-09 13:53
> I think there should be at least the option that limits total number of time urllib3 spends in probing different addresses.

I agree with this.

To not break backward compatibility, an extra argument (`max_connect_timeout` or whatever) could be introduced and eventually passed to [`create_connection`](https://github.com/urllib3/urllib3/blob/5862fe49b380671bb18d5f88674b870370de1ac5/src/urllib3/util/connection.py#L29), where it could be used in its loop over the results of [`getaddrinfo`](https://github.com/urllib3/urllib3/blob/5862fe49b380671bb18d5f88674b870370de1ac5/src/urllib3/util/connection.py#L62) to limit the number of iterations.

Thoughts?

**Comment by barrykan** [comment] 2022-08-29 21:42
> > works as expected
> 
> Expected by whom? I mean I was not expecting it :) For example, curl does not iterate over every possible IP. Why does not urllib3 give up after failed connection to first IP (chosen randomly or by order). Is there a standard or RFC or something that motivates such a behaviour?

I believe curl does iterate over every IP -- at least my version:`curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`. However, it seems to proactively divide `--connect-timeout` by the number of IPs it will try. So if you provide `--connect-timeout 10` to a domain that resolves to 10 IPs, is will try to connect to each IP for only about a second before failing and moving onto the next one.

I can see unexpected behavior from either approach. :+1: to suggestion to keep things for backwards compatibility, but add a new argument `definitely_totally_max_connect_timeout` kwarg (maybe renamed) so we can feel confident that the timeout specified isn't going to be potentially multiplied many times depending on the DNS A records for a domain.

**Comment by sethmlarson** [comment] 2023-05-19 01:19
I'm going to close this as duplicate of #797.

**Closed by sethmlarson** 2023-05-19 01:19 UTC

**Comment by pierky** [comment] 2023-05-19 06:34
> I'm going to close this as duplicate of #797.

Hi, FWIW not sure I agree that this is a duplicate of 797.

Here we're discussing a timeout issue, where we set "timeout = 1 second", but the operation aborts after 6 seconds. And this happens when the domain name is resolved into 6 different IPs.

I understand that this may be the desired behaviour, but I (and others here) believe that it's confusing, at least from a programmer perspective, as it goes against the expectation that `timeout=1` gives us (at least to some of us here). Hence the proposal to introduce an extra argument (`max_connect_timeout`, `definitely_totally_max_connect_timeout`, `stop_running_after` or whatever) to really stop the operation after the desired period of time.
