### ISSUE TITLE
wait_for_read and wait_for_write no longer accepts lists of sockets

### ISSUE THREAD

**Issue by eliasbrange** [urllib3/urllib3#1410] opened 2018-07-03 17:46 UTC
We noticed that we could no longer send in a list of sockets to `util.wait_for_read` and `util.wait_for_write`.

The docs still show the following behaviour:

`urllib3.util.wait_for_read(socks, timeout=None)`
> Waits for reading to be available from a list of sockets or optionally a single socket if passed in. 
> Returns a list of sockets that can be read from immediately.

`urllib3.util.wait_for_write(socks, timeout=None)`
> Waits for writing to be available from a list of sockets or optionally a single socket if passed in. Returns a list of sockets that can be written to immediately.

The change introduced by 9782e1f866aa6d0d176dce8678aee448aeb492dd seems to have removed the possibility of sending in a list of sockets. Is this breaking API change made by purpose? In that case the docs should probably be updated.

**Comment by SethMichaelLarson** [comment] 2018-07-04 00:16
Looks like a regression to me. cc: @njsmith

**Comment by njsmith** [comment] 2018-07-04 00:23
I actually didn't realize that these were documented as a public API. (Which was silly of me, because most of urllib3's internals are documented as public APIs, but there you are.)

My inclination would be to leave the change alone and update the docs, or remove the docs entirely, because urllib3 is not really in the business of providing `select` wrappers and this shouldn't be a public API in the first place. But if it breaks people and we want to keep it working for backwards compatibility, then it would be possible to restore the list-of-sockets functionality, even though nothing inside urllib3 actually uses it.

@eliasbrange What are you using `wait_for_*` for?

Urllib3 maintainers: do you have an opinion on which approach to take?

**Comment by SethMichaelLarson** [comment] 2018-07-04 00:30
I'd say they seem like part of our interface since we're importing them in `urllib3/utils/__init__.py` and we're also doing things in that same file in order to preserve backwards compatibility it seems. I'd rather it not be a part of the public API preferably though.

**Comment by SethMichaelLarson** [comment] 2018-07-04 00:33
Also makes me wonder if we can't optimize to always use `select` when `socket.fileno < 1024` for faster responses.

**Comment by Hernrup** [comment] 2018-07-04 06:02
We (same organization as @eliasbrange) uses a forked version of botocore to fix for a issue were filedescriptors could get exhausted until it gets fixed upstream. In that version the select logic on line https://github.com/boto/botocore/blob/develop/botocore/awsrequest.py#L163 is replaced by something like

```
urllib3.util.wait_for_read([self.sock], 1)
```

So we can surely adapt to the change as long as its clear how its suppose to behave.

**Comment by sigmavirus24** [comment] 2018-07-04 13:30
I agree that I really don't want things like this to be part of the public API. That said, we can't really reasonably restrict what people use from `urllib3.util` when `Retry` is in there and the `Retry` is a publicly documented part of our API.

**Comment by njsmith** [comment] 2018-07-05 00:38
@Hernrup So to make sure I understand, you're saying that you're fine switching to the new behavior, you just want to make sure that you know what the final state will be so you don't end up switching to one thing and then switching back?

@sigmavirus24 So we can certainly move it somewhere else, but that is also a potential backwards compatibility break :-). Of course, we've already released a version that broke anyone using this interface, so maybe now is a great time to remove it entirely from the public API – it won't make things any worse!

I still need a policy call from the maintainers about whether "the urllib3 way" is to restore this to the old API and leave it, restore it and deprecate it at the same time (planning to remove it later), remove it immediately, or what. They all seem defensible to me. Removing it immediately is the easiest.

**Comment by Hernrup** [comment] 2018-07-05 06:16
Yes, @njsmith. That is correct.

I would urge you to fix the semantic versioning chain when resolving this to keep dependency and build systems happy.

My suggestion would be to:
- make a patch release on the 1.23.x feature set restoring the functionality(maybe just rollback?)
- make a breaking release 2.xx to indicate the breaking change, however you choose to implement it.

I think one in general assumes that features are added on minor version bumps and breaking changes only occur on mayor bumps.

We, and I guess many others, by default allow all versions of our dependencies that is larger then the latest feature that we need but smaller then the next mayor version bump. That keeps dependency administration sane in a codebase with a lot of repositories.

**Comment by pquentin** [comment] 2018-10-08 02:16
@SethMichaelLarson Can you please clarify what the accepted solution is? Thanks!

**Comment by njsmith** [comment] 2018-10-08 02:40
@SethMichaelLarson this has been "broken" for almost 6 months now... would switching it back at this point actually help anyone, or would it just re-break everyone who already adapted to the new interface?

...Oh nice, apparently boto is using this now (the new API): https://github.com/boto/botocore/blob/001d16b028910fa55ef1e132e367b3cb18bbba49/botocore/awsrequest.py#L158
:man_facepalming:

**Comment by SethMichaelLarson** [comment] 2018-10-08 03:17
That's true. I guess I'm open to leaving it as single socket because we've only had one report and it seems like we'd actually break more people by changing it back. I guess it stays the way it is.

**Closed by SethMichaelLarson** 2018-10-08 03:17 UTC
Labels: Help Wanted, Proposed Solution Accepted
