### ISSUE TITLE
void

### ISSUE THREAD

**Issue by abebeos** [urllib3/urllib3#3250] opened 2023-12-29 07:25 UTC

**Comment by sethmlarson** [comment] 2023-12-29 21:04
I don't think we should be configuring this at the level of an HTTP response, the response is an IO object so its behavior should be dictated by the consuming user by calling either `.read()` or `.read1()`.

**Comment by abebeos** [comment] 2023-12-30 00:27
> so its behavior should be dictated by the consuming user by calling either `.read()` or `.read1()`.

That can't be done when preloading content, it is hardcoded to `.read()` 

https://github.com/urllib3/urllib3/blob/main/src/urllib3/response.py#L620

(alternative would be to introduce a `preload_via_read1=False` parameter, so the scope is limited to only preloading)

**Comment by sethmlarson** [comment] 2023-12-30 01:09
Does calling `read` versus `read1` matter for preloaded content? We have to block until everything is downloaded anyways, there's no "opportunistic" reads/streaming we can do in that case.

**Comment by abebeos** [comment] 2023-12-30 01:34
I do not know. Me processing this quite abstractly.

`read1` parameter was introduced for `_raw_read()` and `_fp_read()`, but this is not enough to allow for flexibility in testing.

(maybe await some feedback from the author or read1, @smason)

**Comment by abebeos** [comment] 2023-12-30 09:06
Ok, update: it looks like it is not necessary to theorize about this.

Work on https://github.com/urllib3/urllib3/issues/3249 will demonstrate the necessity clearly.

(I've fixed the test-failures 'quick&dirty', needs more time for production quality)

**Comment by sethmlarson** [comment] 2024-01-01 21:32
Brought this up in Discord too, copying here. I think `read1`'s API contract is incompatible with `decode_content` since we can't uphold the IO stream contract of always returning some bytes if `amt > 0` and the stream isn't EOL. For `read()` we can uphold the contract because we're allowed to issue multiple underlying `read()` calls, `read1()` requires us to only issue one syscall though so we can't guarantee that we'll receive enough data in order to emit decompressed data.

**Comment by abebeos** [comment] 2024-01-02 02:05
In this issue here I pick up the existent code, add test-cases (https://github.com/urllib3/urllib3/pull/3248/commits/3496f0f86a50a64ada0d6b5b87c537955e4a11a4, that fail initially), fix test-cases etc. - I am assuming that the basic read1 design is ok.

But: if read1 is already flawed-by-design (as your comment implies), then this should be processed in a new issue, like **"Validate read1()'s usage of 'decode_content' via test-cases"** - something like that.

(personally I think that it's fine to have `decode_content` within read1() - only `cache_content` is obsolete (as its a single read)).

(maybe I should separate the commits into separate PR's, so you could e.g. merge the tests independently of the other stuff? )

**Comment by abebeos** [comment] 2024-01-02 03:04
Please note https://github.com/urllib3/urllib3/pull/3248#issuecomment-1873585491

**Comment by pquentin** [comment] 2024-01-02 10:59
It's not necessarily flawed by design, but it's yet another issue. We could either forbid `decode_content` in read1() or add a warning in the documentation. (For context, we worked hard in https://github.com/urllib3/urllib3/pull/2798 and other places to fix this for `read()`.)

**Comment by illia-v** [comment] 2024-01-03 15:35
The fact that `read1` can make more than one call on the raw stream is a good point. As noted before, this happens and is required only when `decode_content=True`. I'd vote for documenting this properly rather than dropping `decode_content` for `read1`.
One of possible use cases for `read1` is streaming #3216, having the possibility to decode the data is a deal breaker for it.

**Comment by abebeos** [comment] 2024-01-05 00:48
> The fact that `read1` can make more than one call on the raw stream

*can't?

> his streaming https://github.com/urllib3/urllib3/pull/3216, having the possibility to decode the data

*not having?

-

I believe that we can all agree on one thing:

That further work is needed to "Validate/Specify, Revise and Document" read1, and fix any upcoming issues.

Revising code is a strength of me (especially when i'm not very familiar with the code.

Would just need you to apply some bounty-budget to the issues.

**Comment by illia-v** [comment] 2024-01-07 14:36
> > The fact that `read1` can make more than one call on the raw stream
> 
> *can't?

The current version of urllib3's `HTTPResponse` can.

> > his streaming #3216, having the possibility to decode the data
> 
> *not having?

Yes, "not having".

> I believe that we can all agree on one thing:
> 
> That further work is needed to "Validate/Specify, Revise and Document" read1, and fix any upcoming issues.
> 
> Revising code is a strength of me (especially when i'm not very familiar with the code.
> 
> Would just need you to apply some bounty-budget to the issues.

It is unclear what you see as the expected result of #3257 at the moment.
Thank you for bringing up the discussion on the compromise between having `decode_content` for `read1` and following the contract of making up to one call on the raw stream. Since the functionality has not been to any release yet, we can make a choice of either dropping the parameter or documenting that `read1` can make more than one call. The decision should be collective though.

**Comment by abebeos** [comment] 2024-01-08 02:16
> It is unclear what you see as the expected result of #3257 at the moment.

some specs that will allow to write tests, thus read1 can be revised/documented.

(Though I mention a "waterfall" process, in reality it is an iterative process, so I cannot say much in advance)

And note that #3263 comes before.

The only thing (quite) clear to me now is the `read` behavior (see https://github.com/urllib3/urllib3/issues/2799#issuecomment-1872448595), and that `read1` needs some more work. I understand that you have limited budgets, but the, read/read1 is quite basic functionality, and code should be in a "polished" condition.

**Comment by abebeos** [comment] 2024-01-08 04:59
> > > The fact that `read1` can make more than one call on the raw stream
> > 
> > *can't?
> 
> The current version of urllib3's `HTTPResponse` can.

Yes, I wondered about the loop in the current `read1()`.

This would be e.g. the 1st thing to clarify within a spec.

> Since the functionality has not been to any release yet, we can make a choice of either dropping the parameter or documenting that `read1` can make more than one call. The decision should be collective though.

If the (logically derived) specs say "one call only", then you should not overvote it. But I sense that there is a solution to all this.

Not released yet is good, I should be able to have a result within 14 days (tiny chunks daily).

**Comment by abebeos** [comment] 2024-01-08 05:07
> It is unclear what you see as the expected result of #3257 at the moment.

Note that issue #3257 is not a separate bounty (it would be covered by a bounty for the issue here). Spawned it out so it does not get to full here.

**Comment by sethmlarson** [comment] 2024-01-08 21:59
@abebeos Thank you for your interest in contributing to urllib3. I wanted to provide some context into our project and feedback on your approach. I hope that my comment here won't discourage you and instead will help you be more effective towards your goals.

Bounties are only assigned to tasks which have consensus from maintainers and are clearly defined solutions. Tasks which don't have consensus or aren't clearly defined (like this one) won't have bounties assigned until they are clear and agreed upon. It's okay to ask for an issue to be assigned a bounty once it meets this threshold.

Speaking for myself, your approach of opening many issues and PRs all mentioning bounties does not jive well with me, and that may not have been your intent but it is the effect it's had on me.

If your goal is to be paid a bounty (something that we want to do, **we want to pay you!**) you should be working on gaining consensus from maintainers by feeding our context or making concrete and concise proposals. Making tons of comments, linking to other places, marking things as outdated, proposing PRs and then closing them later, all of that gets in the way of maintainers understanding the problem and your proposed solution. We only have so many minutes in a day to spend on open source, so clarity and conciseness count.

I also wanted to note from some of your PRs there is a sense of "merge if it's not incorrect, we can figure it out later". We don't take that approach with this project, doing something for no reason or an unclear reason is a negative outcome even if on the surface the PR is a no-op in terms of value to the project. We value intentionality over getting things done quickly, because one day many years in the future someone will have to know why we made certain changes (and we don't know which ones will matter!)

Again, I hope you understand that this feedback comes from a place of wanting to see you succeed and to ultimately pay you to contribute to our project. Thanks again!

**Comment by abebeos** [comment] 2024-01-08 23:19
Not what I expected after working mostly alone on the project resources over the holidays.

I'm a worker here, came to serve and get some cash in, following mostly this process:

https://urllib3.readthedocs.io/en/latest/contributing.html

>This program is an experiment so if you have positive or negative feedback on the process you can contact the maintainers through one of the above channels.

° respect individuality
* ensure that issues reflect reality

I'll adapt a bit myself, so we may find the middle way.

-

But this i must comment

> I also wanted to note from some of your PRs there is a sense of "merge if it's not incorrect, we can figure it out later". We don't take that approach with this project, doing something for no reason or an unclear reason is a negative outcome even if on the surface the PR is a no-op in terms of value to the project. We value intentionality over getting things done quickly, because one day many years in the future someone (unlikely to be you or me!) will have to know why we made certain changes (and we don't know which ones will matter!)



* My "merge if it's not incorrect, we can figure it out later" is in fact **"merge this iteration now, next iteration will follow later"**.
* Your teams read1 implementation is a "merge, we can figure it out later" (which is nothing bad in a dev repo, if documented clearly in-source)

I'll go on now to delete some redundant stuff, so you don't need to deal with the 'outdated' marked stuff that aggregated over the holidays.

**Comment by abebeos** [comment] 2024-01-09 00:22
> Thank you for your

Replied quickly within https://github.com/urllib3/urllib3/issues/3272#issuecomment-1882033869, to keep the issue clean.

**Closed** 2024-01-09 04:42 UTC
