### ISSUE TITLE
pyopenssl broken in contrib/ , throws TypeError

### ISSUE THREAD

**Issue by makslevental** [urllib3/urllib3#672] opened 2015-07-14 18:25 UTC
Using py 2.7.9 packages

Lines 289 -> 291 in contrib/pyopenssl

makes a call to ssl.SSLError that's broken.

Here's a code snippet that demonstrates

import ssl
import OpenSSL

str(ssl.SSLError('alice',OpenSSL.SSL.Error('bob')))

indeed even

str(ssl.SSLError('foo', Exception('foo')))

reproduces it.

Personally I don't understand wrapping the OpenSSL exception in the ssl exception. Removing the try-except solves the problem handily.
##

**Comment by shazow** [comment] 2015-07-14 18:58
What version of urllib3? Can you try master?

**Comment by ice109** [comment] 2015-07-14 19:20
1.10.4 in requests

**Comment by shazow** [comment] 2015-07-14 19:24
Where are we converting the exception into a str?

**Comment by ice109** [comment] 2015-07-14 19:27
https://github.com/shazow/urllib3/blob/master/urllib3/connectionpool.py#L316 in the first 

if 'timed out' in str(err)

**Comment by shazow** [comment] 2015-07-14 19:30
Mmm good catch. I guess we can get rid of the extra exception arg in SSLError. Interested in doing a PR?

**Comment by ice109** [comment] 2015-07-14 19:36
I don't think you should get rid of the extra exception arg because "bad handshake" isn't descriptive enough. For example, the reason I found is this is because I was completely losing a certificate error and getting the type error instead. I think you should just reraise the OpenSSL exception. 

I've never done one before but sure. What do I do? Just clone, make the change, then submit the pull request?

**Comment by Lukasa** [comment] 2015-07-14 19:39
The problem with re-raising the OpenSSL exception is that it breaks our contract, which is that we only raise `ssl` exceptions. We need to make sure that we don't break that contact.

**Comment by ice109** [comment] 2015-07-14 19:40
Reasonable. Well the solution in the tip is fine, just need requests to synchronize.

**Comment by sigmavirus24** [comment] 2015-07-14 20:29
@ice109 we don't do backports. Requests also will only update this in a 2.8.0 release which @Lukasa and I should probably schedule soon anyway.

**Comment by ice109** [comment] 2015-07-14 20:31
So what is the best practices solution now? To change the code in my copy of urllib?

**Comment by shazow** [comment] 2015-07-15 15:18
Also is this a dupe of #556? I totally missed it.

**Comment by ice109** [comment] 2015-07-15 15:24
it is a dupe of https://github.com/kennethreitz/requests/issues/2524, which @Lukasa  merged into 556 in my opinion erroneously

**Closed** 2018-10-07 19:55 UTC
