### ISSUE TITLE
SOCKS5 Timeout

### ISSUE THREAD

**Issue by CollabSensei** [urllib3/urllib3#2195] opened 2021-04-06 06:52 UTC
### Subject

Using socks5 to connect to a web service, that takes 2-5 minutes to send the response, results in the following error message"urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))"

### Environment

Describe your environment
- urllib3 version 1.26.3.
- Dante Socks5 Proxy 1.42 w/ config
logoutput: /var/log/socks.log
internal: ens160 port = 1080
external: ens160
clientmethod: none
socksmethod: none
user.privileged: root
user.notprivileged: nobody
timeout.connect: 86400
timeout.negotiate: 86400
timeout.tcp_fin_wait: 86400
timeout.io: 86400

client pass {
from: 0.0.0.0/0 to: 0.0.0.0/0
log: error connect disconnect
}
socks pass {
from: 0.0.0.0/0 to: 0.0.0.0/0
log: error connect disconnect
}

```python

url = "https://" + hostname + ":" + api_port + "/axl/"
bodyUpdate = """
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/%version">
<soapenv:Header/>
<soapenv:Body>
    <ns:doSmartLicenseRegister>
        <token>%token</token>
        <force>true</force>
    </ns:doSmartLicenseRegister>
</soapenv:Body>
</soapenv:Envelope>""" 

bodyUpdate = bodyUpdate.replace("%version",str(version))
bodyUpdate = bodyUpdate.replace("%token", getSmartLicenseToken('myToken'))

myHeaders = {
    'SOAPAction': 'CUCM:DB ver=14.0',
    'Accept' : 'text/xml',
    'Content-Type': 'text/xml'
}

proxy = urllib3.contrib.socks.SOCKSProxyManager('socks5://' + vapp_ip + ':1080/', cert_reqs='CERT_NONE')

auth = urllib3.make_headers(basic_auth=f'{username}:{password}')
socket.setdefaulttimeout = 86400
myHeaders.update(auth)
resp = proxy.request(
    'POST',
    url,
    body=bodyUpdate,
    headers=myHeaders,
    timeout=urllib3.Timeout(connect=300, read=300),
    retries=10
)

```

### Steps to Reproduce

Execute above code against Cisco Communication Manager SOAP API. 

### Expected Behavior

Should send HTTPS POST via SOCKS5 and receive a response.

### Actual Behavior

Received the following error message.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by sethmlarson** [comment] 2021-04-18 16:35
Could you use Wireshark to take a PCAP of this network behavior? Otherwise I won't be able to tell you much about what's going on. It sounds like your proxy is replying to things slow, though?

**Comment by sethmlarson** [comment] 2021-05-29 23:04
Closing since we can't reproduce this without a pcap.

**Closed** 2021-05-29 23:03 UTC
