### ISSUE TITLE
parse_url() is not working for ipv6 hostname

### ISSUE THREAD

**Issue by shubham-yewalekar** [urllib3/urllib3#2707] opened 2022-08-09 14:05 UTC
parse_url is not working for ipv6 hostname in the URL because it is unable to parse square brackets for the ipv6 hostname

urllib3 v1.24.3 used to work fine for ipv6 hostnames, but it is breaking from v1.25

**Comment by sethmlarson** [comment] 2022-08-09 14:17
You'll have to give an example, otherwise this will be impossible to reproduce. Our test suite includes many instances of IPv6 working properly with `parse_url` so maybe you're hitting an edge-case?

**Comment by sethmlarson** [comment] 2022-08-12 17:08
Closing for now due to lack of information. We can reopen if information is provided.

**Closed** 2022-08-12 17:08 UTC

**Comment by pquentin** [comment] 2022-08-17 07:05
Also note that we improved URL parsing various times after 1.25.0, please try our latest version.
