### ISSUE TITLE
Can't install urllib3 with certifi using "secure" option

### ISSUE THREAD

**Issue by synergiator** [urllib3/urllib3#2132] opened 2021-01-07 13:56 UTC
### Subject

Can't install latest version of urllib3 together with certifi using ```secure``` option.

### Workaround
Specify certifi installation separately as an explicit dependency.

### Environment

Docker Python Alpine from Docker hub.

```python
OS Linux-5.4.0-58-generic-x86_64-with
Python 3.8.7
# Note: the error happens before urllib3 can be installed
```

### Steps to Reproduce

Here is my test setup reduced to demonstrate the problem:
* Dockerfile
* setup.py

#### Dockerfile
```python
FROM library/python:3.8-alpine
RUN mkdir -p /app/app
RUN apk add gcc musl-dev libffi-dev libressl-dev
ADD setup.py /app
WORKDIR /wheels
RUN pip wheel -e /app
```
#### setup.py

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
from setuptools import setup

__version__ = '0.0.2'

setup(
    name='app',
    version=__version__,
    packages=['app'],
    install_requires=[
        'urllib3[secure]>=1.13'
    ],
)

```

### Expected Behavior
Compilation should work i.e. in my example, Docker image should be created like the following:

```docker build --no-cache -t foo .```

### Actual Behavior

Error as below appears.

```
The conflict is caused by:
    The user requested urllib3 1.26.2 (from /wheels/urllib3-1.26.2-py2.py3-none-any.whl)
    urllib3[secure] 1.26.2 depends on urllib3 1.26.2 (from https://files.pythonhosted.org/packages/f5/71/45d36a8df68f3ebb098d6861b2c017f3d094538c0fb98fa61d4dc43e69b9/urllib3-1.26.2-py2.py3-none-any.whl#sha256=d8ff90d979214d7b4f8ce956e80f4028fc6860e4431f731ea4a8c08f23f99473 (from https://pypi.org/simple/urllib3/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <4))

```

### Additional notes

* Similar problem related to pip/setup tools has been fixed with #706 from version 1.13?

**Comment by sethmlarson** [comment] 2021-01-07 15:26
Strange error message, given very similar inputs I wasn't able to reproduce your issue locally:

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
from setuptools import setup

__version__ = '0.0.2'

setup(
    name='app',
    version=__version__,
    install_requires=[
        'urllib3[secure]>=1.13'
    ],
)
```

```dockerfile
FROM library/python:3.8-alpine
RUN apk add gcc musl-dev libffi-dev libressl-dev
ADD setup.py /
RUN pip wheel -e .
```

I received this output and a successful build:

```
$ docker build --no-cache -t foo .

Sending build context to Docker daemon  3.072kB
Step 1/4 : FROM library/python:3.8-alpine
 ---> 64df5e2068e3
Step 2/4 : RUN apk add gcc musl-dev libffi-dev libressl-dev
 ---> Running in 5f3c211c07cb
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/19) Installing libgcc (9.3.0-r2)
(2/19) Installing libstdc++ (9.3.0-r2)
(3/19) Installing binutils (2.34-r1)
(4/19) Installing gmp (6.2.0-r0)
(5/19) Installing isl (0.18-r0)
(6/19) Installing libgomp (9.3.0-r2)
(7/19) Installing libatomic (9.3.0-r2)
(8/19) Installing libgphobos (9.3.0-r2)
(9/19) Installing mpfr4 (4.0.2-r4)
(10/19) Installing mpc1 (1.1.0-r1)
(11/19) Installing gcc (9.3.0-r2)
(12/19) Installing linux-headers (5.4.5-r1)
(13/19) Installing pkgconf (1.7.2-r0)
(14/19) Installing libffi-dev (3.3-r2)
(15/19) Installing libressl3.1-libcrypto (3.1.2-r0)
(16/19) Installing libressl3.1-libssl (3.1.2-r0)
(17/19) Installing libressl3.1-libtls (3.1.2-r0)
(18/19) Installing libressl-dev (3.1.2-r0)
(19/19) Installing musl-dev (1.1.24-r10)
Executing busybox-1.31.1-r19.trigger
OK: 173 MiB in 54 packages
Removing intermediate container 5f3c211c07cb
 ---> 3385d1afd744
Step 3/4 : ADD setup.py /
 ---> 2891febeb3ab
Step 4/4 : RUN pip wheel -e .
 ---> Running in 4ef2a0ca701f
Obtaining file:///
Collecting urllib3[secure]>=1.13
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting cryptography>=1.3.4
  Downloading cryptography-3.3.1.tar.gz (539 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting cffi>=1.12
  Using cached cffi-1.14.4-cp38-cp38-linux_x86_64.whl
Collecting idna>=2.0.0
  Downloading idna-3.1-py3-none-any.whl (58 kB)
Collecting pyOpenSSL>=0.14
  Downloading pyOpenSSL-20.0.1-py2.py3-none-any.whl (54 kB)
Collecting six>=1.4.1
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting certifi
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Saved /urllib3-1.26.2-py2.py3-none-any.whl
Saved /cffi-1.14.4-cp38-cp38-linux_x86_64.whl
Saved /idna-3.1-py3-none-any.whl
Saved /pyOpenSSL-20.0.1-py2.py3-none-any.whl
Saved /six-1.15.0-py2.py3-none-any.whl
Saved /certifi-2020.12.5-py2.py3-none-any.whl
Saved /pycparser-2.20-py2.py3-none-any.whl
Building wheels for collected packages: app, cryptography
  Building wheel for app (setup.py): started
  Building wheel for app (setup.py): finished with status 'done'
  Created wheel for app: filename=app-0.0.2-py3-none-any.whl size=988 sha256=3bbb7b0e257ce2c432bcdfddb16b3c3b86c591ee5e3616519f38b8d2b1255818
  Stored in directory: /tmp/pip-ephem-wheel-cache-x0_e77ml/wheels/71/14/ca/3328a396c88af22398f5b4dd8e8fc154afa1b3361207ad1ed1
  Building wheel for cryptography (PEP 517): started
  Building wheel for cryptography (PEP 517): finished with status 'done'
  Created wheel for cryptography: filename=cryptography-3.3.1-cp38-cp38-linux_x86_64.whl size=363890 sha256=b0d4cd22ab8f005536a7c757a12bd9b3026cb15570a59f531f4e10ab0cc97aa8
  Stored in directory: /root/.cache/pip/wheels/9b/bd/12/c040f2df6b28138b66b0361cd218180a278b95763fc2466951
Successfully built app cryptography
Removing intermediate container 4ef2a0ca701f
 ---> 4f9160bd61be
Successfully built 4f9160bd61be
Successfully tagged foo:latest
```

**Comment by sethmlarson** [comment] 2021-01-14 03:53
Closing this as not able to reproduce.

**Closed by sethmlarson** 2021-01-14 03:53 UTC

**Comment by pradyunsg** [comment] 2021-01-21 22:20
FWIW, this error is happening because pip is selecting different urllib3 packages (for some reason - more on this below). That's being rejected by the resolver due to mismatching URLs - benefits of being strict. :) 

I'm not sure how you're getting those different URLs though, since pip's not going to be looking at /wheels unless you tell it to (and you haven't), so the results from @sethmlarson's attempt at reproducing this is the exact behaviour I'd expect.

**Comment by pradyunsg** [comment] 2021-01-21 22:23
If this is still a thing tho, please provide the output of the docker build, like the comment above. :)

**Comment by synergiator** [comment] 2021-01-21 22:32
I am neither able to reproduce it furthermore in the simplified setup. Must be some environment specific glitch.
