### ISSUE TITLE
chunked encoding response content.

### ISSUE THREAD

**Issue by yoga-king** [urllib3/urllib3#2328] opened 2021-07-14 07:30 UTC
### Subject
In Ubuntu, it does not receive chunked encoding response content.

### Environment

```python
>>> print("OS", platform.platform())
OS Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-glibc2.27
>>> print("Python", platform.python_version())
Python 3.8.0
>>> print("urllib3", urllib3.__version__)
urllib3 1.26.6
```

### Steps to Reproduce

```
import platform
import urllib3

print("OS", platform.platform())
print("Python", platform.python_version())
print("urllib3", urllib3.__version__)

url = "https://cargoonline.xyz/image"
http = urllib3.PoolManager()
resp = http.request("GET", url)


print(resp.headers)
print(resp.data)
```

### Expected Behavior
run in Mac

<img width="905" alt="스크린샷 2021-07-15 오후 2 25 28" src="https://user-images.githubusercontent.com/87413415/125733535-d8ac981e-34c7-46a3-b71d-3d466ab49412.png">

### Actual Behavior
run in Ubuntu -> empty response content

<img width="1169" alt="스크린샷 2021-07-14 오후 4 28 15" src="https://user-images.githubusercontent.com/87413415/125581115-6e6b0d8d-9f68-42a9-a462-73753fa0b6c4.png">

**Comment by pquentin** [comment] 2021-07-14 09:00
Can you please try using urllib3 1.26.6 on macOS too?

**Comment by yoga-king** [comment] 2021-07-15 05:27
@pquentin Yes, I updated

**Comment by pquentin** [comment] 2021-07-15 07:44
I'm not reproducing on Docker from macOS:

```
>>> import platform
>>> import urllib3
>>> print("OS", platform.platform())
OS Linux-5.10.25-linuxkit-x86_64-with-glibc2.28
>>> print("Python", platform.python_version())
Python 3.9.6
>>> print("urllib3", urllib3.__version__)
urllib3 1.26.6
>>> url = "https://cargoonline.xyz/image"
>>> http = urllib3.PoolManager()
>>> resp = http.request("GET", url)
>>> print(resp.status)
200
>>> print(resp.headers)
HTTPHeaderDict({'Date': 'Thu, 15 Jul 2021 07:35:04 GMT', 'Content-Type': 'image/png', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Powered-By': 'PHP/8.0.3', 'Cache-Control': 'no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0', 'Pragma': 'no-cache', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=Dk7%2FHV8G0DwRpWB9jnrg7woSyr1r7FJCXfotIRUd7pXkfzpTHBG1%2FYLEViksfFr2VghqmO7hoNLHYuPpUPhqsDzS5sllP%2Fzd83hFWaNbl6Ba%2BNDEbIurqK9BHUw0ZuYzXN0%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '66f14fd7dabfc73c-RUN', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400'})
>>> print(resp.data[:100])
b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x01\xc3\x00\x00\x00>\x08\x06\x00\x00\x00W\xfdp\xad\x00\x00\x00\x01sRGB\x00\xae\xce\x1c\xe9\x00\x00\x00\x04gAMA\x00\x00\xb1\x8f\x0b\xfca\x05\x00\x00\x00\tpHYs\x00\x00\x16%\x00\x00\x16%\x01IR$\xf0\x00\x00:mIDATx^\xed\x9d\x07@\x14\xc7\xfb'
```

You seem to be using RHEL 7, which is really old. Have you tried using another tool like curl to fetch this data? For now, closing as unable to reproduce.

**Closed by pquentin** 2021-07-15 07:44 UTC

**Comment by yoga-king** [comment] 2021-07-22 07:26
@pquentin
curl doesn't work too. 
What is the minimum required kernel version ?

**Comment by pquentin** [comment] 2021-07-23 09:44
We don't use curl, no, so that proves this isn't a urllib3 bug. It's probably not kernel related, maybe the issue is the OpenSSL version? In any case, we can't help you fix this since this isn't a urllib3 bug. You can try StackOverflow or Super User.
