### ISSUE TITLE
Flawed redirect handling

### ISSUE THREAD

**Issue by impredicative** [urllib3/urllib3#1555] opened 2019-03-19 19:39 UTC
I'm unable to read https://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract

It's evidently not because of cookies. It's because of issues with URL parsing and/or redirect handling.

```python
urllib3.__version__
'1.24.1'
http = urllib3.PoolManager()
http.request('GET', 'https://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract')
/home/devuser/venv/urltitle/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/devuser/venv/urltitle/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/devuser/venv/urltitle/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/devuser/venv/urltitle/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/devuser/venv/urltitle/lib/python3.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/home/devuser/venv/urltitle/lib/python3.7/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/devuser/venv/urltitle/lib/python3.7/site-packages/urllib3/poolmanager.py", line 359, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/home/devuser/venv/urltitle/lib/python3.7/site-packages/urllib3/poolmanager.py", line 359, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/home/devuser/venv/urltitle/lib/python3.7/site-packages/urllib3/poolmanager.py", line 359, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/home/devuser/venv/urltitle/lib/python3.7/site-packages/urllib3/poolmanager.py", line 349, in urlopen
    retries = retries.increment(method, url, response=response, _pool=conn)
  File "/home/devuser/venv/urltitle/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='secure.jbs.elsevierhealth.com', port=443): Max retries exceeded with url: https://secure.jbs.elsevierhealth.com/action/getSharedSiteSession?rc=2&redirect=https%3A%2F%2Fwww.annemergmed.com%2Farticle%2FS0196-0644%2899%2970271-4%2Fabstract (Caused by ResponseError('too many redirects'))
```

**Comment by sethmlarson** [comment] 2019-03-19 21:42
Looks like this website sends you in a redirect loop if you're not doing something that a browser would normally do? (Cookies, authenticating?)

```python
import urllib3
http = urllib3.PoolManager()

http.request("GET", "https://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract", retries=urllib3.util.Retry(redirect=False)).headers["Location"]
# https://signin.acep.org/idp?autosso=true&redir=http://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract

http.request("GET", "https://signin.acep.org/idp?autosso=true&redir=http://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract", retries=urllib3.util.Retry(redirect=False)).headers["Location"]
# /idp/Account/Login?ReturnUrl=%2fidp%3fautosso%3dtrue%26redir%3dhttp%3a%2f%2fwww.annemergmed.com%2farticle%2fS0196-0644(99)70271-4%2fabstract&autosso=true&redir=http://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract

http.request("GET", "https://signin.acep.org/idp/Account/Login?ReturnUrl=%2fidp%3fautosso%3dtrue%26redir%3dhttp%3a%2f%2fwww.annemergmed.com%2farticle%2fS0196-0644(99)70271-4%2fabstract&autosso=true&redir=http://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract", retries=urllib3.util.Retry(redirect=False)).headers["Location"]
# http://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract

http.request("GET", "http://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract", retries=urllib3.util.Retry(redirect=False)).headers["Location"]
# https://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract

# ... and the cycle continues
```

This is expected behavior based on what the server is doing, urllib3 can't do anything about this unfortunately. Closing for now.

**Closed by sethmlarson** 2019-03-19 21:42 UTC

**Comment by impredicative** [comment] 2019-03-19 21:47
How is it that `requests` works fine?

```python
>>> import requests
>>> requests.__version__
'2.21.0'
>>> requests.get('https://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract')
<Response [200]>
```
I think this bug exists even if cookies are accepted.

**Comment by sethmlarson** [comment] 2019-03-19 22:29
The reason that requests works is because there's no limit on the number of redirects by default which is unhelpfully a few more than our default.
```python
>>> import requests
>>> r = requests.get("https://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract")
>>> r
<Response [200]>
>>> r.history
[<Response [302]>, <Response [302]>, <Response [302]>, <Response [302]>, <Response [302]>, <Response [302]>, <Response [302]>, <Response [302]>, <Response [302]>, <Response [302]>, <Response [301]>]
>>> len(r.history)
11
```

So doing the following works:

```python
>>> import urllib3
>>> http = urllib3.PoolManager()
>>> r = http.request("GET", "https://www.annemergmed.com/article/S0196-0644(99)70271-4/abstract", retries=urllib3.util.Retry(total=13, redirect=13))
>>> r.status
200
```
