### ISSUE TITLE
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by rishav667** [urllib3/urllib3#3353] opened 2024-02-22 15:21 UTC
can anyone help me with the below error
Error occurred ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
I am using requests==2.28.2 version and while logging into tableau using rest api the error is coming.
As I am first creating the session and then doing the post request.
The issue is coming only in prod environment

**Comment by sigmavirus24** [comment] 2024-02-22 15:49
Duplicate of https://github.com/psf/requests/issues/6645

**Closed by sigmavirus24** 2024-02-22 15:49 UTC
