### ISSUE TITLE
[REG 1.26.15 -> 2.0.2] SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by orgads** [urllib3/urllib3#3031] opened 2023-05-15 15:11 UTC
### Subject

When I try to connect to a TLS server that uses weak cipher (`AES256-GCM-SHA384`), connection fails even if I pass `verify=False`.

This worked with 1.26.15.

### Environment

```
OS Linux-5.10.0-21-cloud-amd64-x86_64-with
Python 3.11.3
urllib3 2.0.2
```

### Steps to Reproduce

Server (Apache) is configured with:
```
SSLCipherSuite !EDH:!ADH:!DSS:!RC4:HIGH:!3DES:!aNULL:!DH:!ECDH
```

Client:
```python
import requests
requests.get("https://my-server/path", verify=False)
```

### Expected Behavior

It should connect. If I allow ECDH (by removing `:!ECDH`), the negotiated cipher is `ECDHE-RSA-AES256-GCM-SHA384`, and connection succeeds.

This might be intended, but I didn't find it documented anywhere.

### Actual Behavior

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 774, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 459, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 503, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='1.2.3.4', port=443): Max retries exceeded with url: /path (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1002)')))
```

**Comment by orgads** [comment] 2023-05-15 15:42
Note: This only happens with Python>=3.10. Python 3.9 still works.

**Comment by sethmlarson** [comment] 2023-05-16 02:04
urllib3 v2.0 uses whatever the system (or OpenSSL's) configured cipher suites are by default. My guess is that your OpenSSL is configured to use non-weak ciphers, so when the handshake happens there is no overlap between the client and server. The work-around is to either configure the exact ciphersuite you need in urllib3 or to configure your OpenSSL to allow a weaker ciphersuite (not recommended, as it would impact all applications).

Going to close this as I believe this is the issue you're facing, if there's additional information we can reopen this issue.

**Closed by sethmlarson** 2023-05-16 02:04 UTC

**Comment by orgads** [comment] 2023-05-16 09:36
Thank you.

**Comment by elminson** [comment] 2023-06-03 02:08
@orgads I had create a PR that will solve this. 
@sethmlarson the issue is when no default context is provided to ssl package 
PR: https://github.com/urllib3/urllib3/pulls
Issue: https://github.com/urllib3/urllib3/issues/3059
