### ISSUE TITLE
HTTPConnection pool connect timeouts throw read timeout exceptions

### ISSUE THREAD

**Issue by typenil** [urllib3/urllib3#1461] opened 2018-10-22 23:06 UTC
The `HTTPConnectionPool` method `_raise_timeout` only raises a `ReadTimeoutError`, but gets reused during the connection validation phase:

https://github.com/urllib3/urllib3/blob/cd7cfa613b2678e700597d098ce9bbdc934863e6/src/urllib3/connectionpool.py#L346

I could be misunderstanding this, but it seems like a `SocketTimeout` thrown from `_validate_conn` should result in a `ConnectTimeoutError`.

If a `ConnectTimeoutError` isn't appropriate - it would be helpful to change the exception message to reflect which timeout was used; currently all timeouts get reported as read timeouts, despite the fact that the connection timeout also get passed in:

https://github.com/urllib3/urllib3/blob/cd7cfa613b2678e700597d098ce9bbdc934863e6/src/urllib3/connectionpool.py#L306

I spent a lot of trying to figure out how I'd sent the wrong timeout format, but it turns out the error just wasn't describing the timeout I expected.

**Comment by pquentin** [comment] 2018-10-23 06:08
Nice catch! I guess that `_raise_timeout` could accept an exception class, which would be either ReadTimeoutError or ConnectTimeoutError. That way, the correct exception would be raised.

@SethMichaelLarson What do you think?

**Comment by SethMichaelLarson** [comment] 2018-10-23 13:14
I'm pretty sure this is duplicate of #1366 and requests/requests#4590, see discussion there as to why this exception is raised as opposed to `ConnectionTimeoutError`.

**Closed by SethMichaelLarson** 2018-10-23 13:14 UTC

**Comment by typenil** [comment] 2018-10-23 16:43
It is a duplicate. Though I don't think that discussion adequately explains why it's a `ReadTimeoutError`. Seems like the arguments made support the opposite moreso.

But supposing that `ReadTimeoutError` is more appropriate, that discussion doesn't address why the connect timeout is labeled as a read timeout in the exception. If `ReadTimeoutError` is still appropriate, it would be less confusing if the timeout value wasn't misidentified as a the read timeout, specifically. Or why the connect timeout is used in a call that's only supposed to raise a `ReadTimeoutError`.
