### ISSUE TITLE
InvalidChunkLength errors raised can't be pickled -> unpickled

### ISSUE THREAD

**Issue by Tarty** [urllib3/urllib3#2893] opened 2023-01-20 08:52 UTC
### Subject

The impacted application is using a concurrent.futures.ProcessPoolExecutor (and the library apscheduler) to schedule and execute a set of jobs. When one job is raising an error, the error instance is pickled to be retrieved by the main process that will unpickle it.

Lately, an API used as source for one of the job was not accessible anymore due to an internal DNS issue. This as expected led to the job raising an error.

However, instead of being handled as a job that failed, the main process crashed and the process pool was broken.

After having a look, it looks like the error raised by the job couldn't be pickled/unpickled, and that this was the cause of the main process crashing.

Here is the full traceback of the error raised by the job that tried to download data from the unavailable API:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 761, in _update_chunk_length
self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 444, in _error_catcher
yield
File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 828, in read_chunked
self._update_chunk_length()
File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 765, in _update_chunk_length
raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 816, in generate
yield from self.raw.stream(chunk_size, decode_content=True)
File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 624, in stream
for line in self.read_chunked(amt, decode_content=decode_content):
File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 816, in read_chunked
with self._error_catcher():
File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
self.gen.throw(typ, value, traceback)
File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 461, in _error_catcher
raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

and the error in the main process that ensued:

```
concurrent.futures.process._RemoteTraceback:
'''
Traceback (most recent call last):
File "/usr/local/lib/python3.10/concurrent/futures/process.py", line 387, in wait_result_broken_or_wakeup
result_item = result_reader.recv()
File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 251, in recv
return _ForkingPickler.loads(buf.getbuffer())
TypeError: InvalidChunkLength.__init__() missing 1 required positional argument: 'length'
'''

The above exception was the direct cause of the following exception:

concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

### Environment

Running in python 3.10.9-bullseye Docker image
Python 3.10.9
urllib3==1.26.14

### Steps to Reproduce

```python
import pickle
from urllib3 import HTTPResponse
from urllib3.exceptions import InvalidChunkLength

error = InvalidChunkLength(HTTPResponse(), b'')
pickled = pickle.dumps(error)
pickle.loads(pickled)
```

### Expected Behavior

The above snippet wouldn't raise an error. An InvalidChunkLength error raised by urllib3 can be pickled an unpickled.

### Actual Behavior

The above snippet leads to the following error being raised:

```
In [1]: import pickle
   ...: from urllib3 import HTTPResponse
   ...: from urllib3.exceptions import InvalidChunkLength
   ...:
   ...: error = InvalidChunkLength(HTTPResponse(), b'')
   ...: pickled = pickle.dumps(error)
   ...: pickle.loads(pickled)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 7
      5 error = InvalidChunkLength(HTTPResponse(), b'')
      6 pickled = pickle.dumps(error)
----> 7 pickle.loads(pickled)

TypeError: InvalidChunkLength.__init__() missing 1 required positional argument: 'length'
```

-----

Thank you for your time and attention!

**Comment by sethmlarson** [comment] 2023-02-05 19:58
We don't test the picklability of any of our exception classes, if you'd be willing to contribute this without much of a problem I could see it being useful but since this is the first report in a long time about pickling exceptions I'm not sure how broad the need is.

**Comment by Dobatymo** [comment] 2023-02-23 04:27
I can reproduce this with `urllib3-1.26.14`, but not with the latest commit [5e072876b81e8adb30df8cdffbc756b7af883ca4](https://github.com/urllib3/urllib3/commit/5e072876b81e8adb30df8cdffbc756b7af883ca4)
. So it might be fixed already.

**Comment by sethmlarson** [comment] 2023-03-19 18:27
If this is fixed in main then I'm going to close this issue.

**Closed by sethmlarson** 2023-03-19 18:27 UTC
