### ISSUE TITLE
urllib3 version 1.26.2 doesn't work when it connects via proxy

### ISSUE THREAD

**Issue by vankhoa011** [urllib3/urllib3#2135] opened 2021-01-14 07:04 UTC
### Subject
Got ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:877)

### Environment

```
boto3==1.16.54
botocore==1.19.54
certifi==2020.12.5
jmespath==0.10.0
python-dateutil==2.8.1
s3transfer==0.3.4
six==1.15.0
urllib3==1.26.2
```

### Steps to Reproduce

```
import urllib3
http = urllib3.ProxyManager('https://squid:3128')
r = http.request('GET', 'https://apache.org')
```
And got the issue

```
  File "/home/khnguyen/khoatest/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/khnguyen/khoatest/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/khnguyen/khoatest/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/khnguyen/khoatest/lib64/python3.6/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/home/khnguyen/khoatest/lib64/python3.6/site-packages/urllib3/util/ssl_.py", line 429, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/home/khnguyen/khoatest/lib64/python3.6/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:877)
```

However, It works with **urllib3 version 1.25.4**
I don't know what the change is recently .

**Comment by pquentin** [comment] 2021-01-14 10:16
Squid exposes HTTP at port 3128, not HTTPS. Can you try this instead?

```
import urllib3
http = urllib3.ProxyManager('http://squid:3128')
r = http.request('GET', 'https://apache.org')
```

Closing as a duplicate of https://github.com/urllib3/urllib3/issues/2075.

**Closed by pquentin** 2021-01-14 10:16 UTC

**Comment by vankhoa011** [comment] 2021-01-15 14:21
@pquentin : Thanks . It works correctly.
