### ISSUE TITLE
Issues running test suite under Python 3.9

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1772] opened 2019-12-28 15:42 UTC
Tornado is an issue due to the `collections.abc` change switching from deprecation warnings to errors in 3.9. Unfortunately moving to the latest Tornado version also doesn't work and might be more work than it's worth. I'm thinking if the issue is only to do with `collections.abc` we vendor the library and make the modification ourselves.

**Comment by tirkarthi** [comment] 2020-01-04 17:46
Is there a log of the warnings emitted? Quick search of tornado code doesn't show any instances of using ABC from collections module directly.

**Comment by sethmlarson** [comment] 2020-01-04 17:51
@tirkarthi It's the specific version we're using, we're pinned <6 for now because migrating breaks a lot of tests. We could go the other way towards trying to upgrade to the latest Tornado but I feel like that's a lot more work than vendoring 5.1.1.

**Comment by pquentin** [comment] 2020-01-06 10:25
> we're pinned <6 for now because migrating breaks a lot of tests.

The issue is that Tornado 6+ does not support Python 2.7 because it relies asyncio. But I just checked and Tornado 6+ works fine on Python 3.5+ (including 3.9). Since Tornado 6 and 5 share the same API for our purposes, I think the better option is to use Tornado 6 on Python 3 and Tornado 5 on Python 2. That would be a two lines change. :)

If you're OK with this I'll open a PR once the build is fixed by #1774.

**Closed** 2020-01-07 04:05 UTC
