### ISSUE TITLE
Python 3.11.0 alpha 7 times out in CI

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2602] opened 2022-05-03 06:48 UTC
<details>
<summary>On April 14th, 3.11-dev finished in 3m17s: <a href="https://github.com/urllib3/urllib3/runs/6022395444?check_suite_focus=true">https://github.com/urllib3/urllib3/runs/6022395444?check_suite_focus=true</a> </summary>

```
Thu, 14 Apr 2022 10:28:07 GMT
Run ./ci/run_tests.sh
Thu, 14 Apr 2022 10:28:08 GMT nox > Running session test-3.11
Thu, 14 Apr 2022 10:28:08 GMT nox > Creating virtual environment (virtualenv) using python3.11 in .nox/test-3-11
Thu, 14 Apr 2022 10:28:09 GMT nox > python -m pip install -r dev-requirements.txt
Thu, 14 Apr 2022 10:28:16 GMT nox > python -m pip install '.[socks,secure,brotli]'
Thu, 14 Apr 2022 10:28:23 GMT nox > pip --version
Thu, 14 Apr 2022 10:28:23 GMT pip 22.0.4 from /home/runner/work/urllib3/urllib3/.nox/test-3-11/lib/python3.11/site-packages/pip (python 3.11)
Thu, 14 Apr 2022 10:28:23 GMT nox > python --version
Thu, 14 Apr 2022 10:28:23 GMT Python 3.11.0a6
Thu, 14 Apr 2022 10:28:23 GMT nox > python -c 'import struct; print(struct.calcsize('"'"'P'"'"') * 8)'
Thu, 14 Apr 2022 10:28:23 GMT 64
Thu, 14 Apr 2022 10:28:23 GMT nox > python -m OpenSSL.debug
Thu, 14 Apr 2022 10:28:24 GMT pyOpenSSL: 22.0.0
Thu, 14 Apr 2022 10:28:24 GMT cryptography: 35.0.0
Thu, 14 Apr 2022 10:28:24 GMT cffi: 1.15.0
Thu, 14 Apr 2022 10:28:24 GMT cryptography's compiled against OpenSSL: OpenSSL 1.1.1l  24 Aug 2021
Thu, 14 Apr 2022 10:28:24 GMT cryptography's linked OpenSSL: OpenSSL 1.1.1l  24 Aug 2021
Thu, 14 Apr 2022 10:28:24 GMT Python's OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
Thu, 14 Apr 2022 10:28:24 GMT Python executable: /home/runner/work/urllib3/urllib3/.nox/test-3-11/bin/python
Thu, 14 Apr 2022 10:28:24 GMT Python version: 3.11.0a6 (main, Mar 19 2022, 19:18:31) [GCC 9.4.0]
Thu, 14 Apr 2022 10:28:24 GMT Platform: linux
Thu, 14 Apr 2022 10:28:24 GMT sys.path: ['/home/runner/work/urllib3/urllib3', '/opt/hostedtoolcache/Python/3.11.0-alpha.6/x64/lib/python311.zip', '/opt/hostedtoolcache/Python/3.11.0-alpha.6/x64/lib/python3.11', '/opt/hostedtoolcache/Python/3.11.0-alpha.6/x64/lib/python3.11/lib-dynload', '/home/runner/work/urllib3/urllib3/.nox/test-3-11/lib/python3.11/site-packages']
Thu, 14 Apr 2022 10:28:24 GMT nox > python -bb -m coverage run --parallel-mode -m pytest -r a --color=yes --tb=native --no-success-flaky-report test/
Thu, 14 Apr 2022 10:28:24 GMT /home/runner/work/urllib3/urllib3/.nox/test-3-11/lib/python3.11/site-packages/pytest_freezegun.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
Thu, 14 Apr 2022 10:28:24 GMT   from distutils.version import LooseVersion
Thu, 14 Apr 2022 10:28:28 GMT ============================= test session starts ==============================
Thu, 14 Apr 2022 10:28:28 GMT platform linux -- Python 3.11.0a6, pytest-7.0.0, pluggy-1.0.0
Thu, 14 Apr 2022 10:28:28 GMT rootdir: /home/runner/work/urllib3/urllib3, configfile: setup.cfg
Thu, 14 Apr 2022 10:28:28 GMT plugins: timeout-2.1.0, flaky-3.7.0, freezegun-0.4.2
Thu, 14 Apr 2022 10:28:28 GMT collected 2167 items
Thu, 14 Apr 2022 10:28:28 GMT
Thu, 14 Apr 2022 10:28:28 GMT test/test_collections.py ......................................          [  1%]
Thu, 14 Apr 2022 10:28:28 GMT test/test_compatibility.py .                                             [  1%]
Thu, 14 Apr 2022 10:28:28 GMT test/test_connection.py ..................                               [  2%]
Thu, 14 Apr 2022 10:28:28 GMT test/test_connectionpool.py ............................................ [  4%]
Thu, 14 Apr 2022 10:28:28 GMT ...............................                                          [  6%]
Thu, 14 Apr 2022 10:28:28 GMT test/test_exceptions.py ..............                                   [  6%]
Thu, 14 Apr 2022 10:28:29 GMT test/test_fields.py ....................                                 [  7%]
Thu, 14 Apr 2022 10:28:29 GMT test/test_filepost.py .........                                          [  8%]
Thu, 14 Apr 2022 10:28:29 GMT test/test_no_ssl.py ..                                                   [  8%]
Thu, 14 Apr 2022 10:28:29 GMT test/test_poolmanager.py ..............................                  [  9%]
Thu, 14 Apr 2022 10:28:29 GMT test/test_proxymanager.py ......                                         [  9%]
Thu, 14 Apr 2022 10:28:29 GMT test/test_queue_monkeypatch.py .                                         [  9%]
Thu, 14 Apr 2022 10:28:29 GMT test/test_response.py .................................................. [ 12%]
Thu, 14 Apr 2022 10:28:29 GMT ....................                                                     [ 13%]
Thu, 14 Apr 2022 10:28:29 GMT test/test_retry.py ..................................................... [ 15%]
Thu, 14 Apr 2022 10:28:29 GMT .......                                                                  [ 15%]
Thu, 14 Apr 2022 10:28:30 GMT test/test_ssl.py ..........................................              [ 17%]
Thu, 14 Apr 2022 10:28:31 GMT test/test_ssltransport.py .................                              [ 18%]
Thu, 14 Apr 2022 10:28:33 GMT test/test_util.py ...................................................... [ 21%]
Thu, 14 Apr 2022 10:28:35 GMT ........................................................................ [ 24%]
Thu, 14 Apr 2022 10:28:37 GMT ........................................................................ [ 27%]
Thu, 14 Apr 2022 10:28:39 GMT ....................................s...s............................... [ 31%]
Thu, 14 Apr 2022 10:28:41 GMT .......................................................                  [ 33%]
Thu, 14 Apr 2022 10:29:28 GMT test/test_wait.py .............                                          [ 34%]
Thu, 14 Apr 2022 10:29:30 GMT test/contrib/test_pyopenssl.py ......................................... [ 36%]
Thu, 14 Apr 2022 10:29:32 GMT .........................ssssssssssssss.sssssssss.ssss.ssss.sssssssssss. [ 39%]
Thu, 14 Apr 2022 10:29:36 GMT s...ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 42%]
Thu, 14 Apr 2022 10:29:40 GMT ssssssssssssssssssssssssssss..........................................s. [ 46%]
Thu, 14 Apr 2022 10:29:47 GMT ........................................s.....s....s.................... [ 49%]
Thu, 14 Apr 2022 10:29:50 GMT ..............                                                           [ 50%]
Thu, 14 Apr 2022 10:29:50 GMT test/contrib/test_pyopenssl_dependencies.py ..                           [ 50%]
Thu, 14 Apr 2022 10:29:51 GMT test/contrib/test_securetransport.py sssssssssssssssssssssssssssssssssss [ 51%]
Thu, 14 Apr 2022 10:29:53 GMT ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 55%]
Thu, 14 Apr 2022 10:29:55 GMT ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 58%]
Thu, 14 Apr 2022 10:29:56 GMT sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss    [ 61%]
Thu, 14 Apr 2022 10:29:57 GMT test/contrib/test_socks.py ...................                           [ 62%]
Thu, 14 Apr 2022 10:29:59 GMT test/with_dummyserver/test_chunked_transfer.py .................         [ 63%]
Thu, 14 Apr 2022 10:30:01 GMT test/with_dummyserver/test_connectionpool.py ........................... [ 64%]
Thu, 14 Apr 2022 10:30:04 GMT ........................................................................ [ 67%]
Thu, 14 Apr 2022 10:30:07 GMT ........................................................................ [ 71%]
Thu, 14 Apr 2022 10:30:11 GMT ........................................................................ [ 74%]
Thu, 14 Apr 2022 10:30:14 GMT ........................................................................ [ 77%]
Thu, 14 Apr 2022 10:30:21 GMT .......................................                                  [ 79%]
Thu, 14 Apr 2022 10:30:23 GMT test/with_dummyserver/test_https.py ssssssssssssss.sssssssss.ssss.ssss.s [ 81%]
Thu, 14 Apr 2022 10:30:25 GMT ssssssssss.sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 84%]
Thu, 14 Apr 2022 10:30:28 GMT ssssssssssssssssssssssssssssssssssss.................................... [ 87%]
Thu, 14 Apr 2022 10:30:38 GMT ................................................s..........s............ [ 91%]
Thu, 14 Apr 2022 10:30:39 GMT ....                                                                     [ 91%]
Thu, 14 Apr 2022 10:30:40 GMT test/with_dummyserver/test_no_ssl.py ..                                  [ 91%]
Thu, 14 Apr 2022 10:30:41 GMT test/with_dummyserver/test_poolmanager.py .............................. [ 92%]
Thu, 14 Apr 2022 10:30:42 GMT .............                                                            [ 93%]
Thu, 14 Apr 2022 10:30:45 GMT test/with_dummyserver/test_proxy_poolmanager.py ....s................... [ 94%]
Thu, 14 Apr 2022 10:31:09 GMT .............s...........                                                [ 95%]
Thu, 14 Apr 2022 10:31:14 GMT test/with_dummyserver/test_socketlevel.py .............................. [ 97%]
Thu, 14 Apr 2022 10:31:25 GMT .................................................s.s.s.........          [100%]
Thu, 14 Apr 2022 10:31:25 GMT
Thu, 14 Apr 2022 10:31:25 GMT =============================== warnings summary ===============================

(Excluded as the warning summary is very verbose and unlikely to be relevant)

Thu, 14 Apr 2022 10:31:25 GMT -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
Thu, 14 Apr 2022 10:31:25 GMT =========================== short test summary info ============================
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [2] test/test_util.py:508: only run if a brotli library is absent
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [67] test/with_dummyserver/test_https.py:87: Skipping base test class
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [2] test/with_dummyserver/test_https.py:756: Skipping base test class
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [2] test/with_dummyserver/test_https.py:772: Skipping base test class
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [2] test/with_dummyserver/test_https.py:791: Skipping base test class
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [6] test/with_dummyserver/test_https.py:821: Skipping base test class
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [2] test/with_dummyserver/test_https.py:841: Skipping base test class
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [2] test/with_dummyserver/test_https.py:862: Skipping base test class
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [3] test/with_dummyserver/test_https.py:892: requires OpenSSL 1.1.1+
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [2] test/with_dummyserver/test_https.py:96: Skipping base test class
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [96] test/conftest.py:319: Test requires TLSv1
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [96] test/conftest.py:326: Test requires TLSv1.1
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [4] test/with_dummyserver/test_https.py:100: ssl.PROTOCOL_TLSv1_3 isn't available
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [248] test/contrib/test_securetransport.py:20: Could not import SecureTransport: ImportError('Only macOS is supported')
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [1] test/with_dummyserver/test_proxy_poolmanager.py:103: Test only runs with SecureTransport
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [1] test/with_dummyserver/test_proxy_poolmanager.py:585: Test is expected to fail due to urllib3/urllib3#2577
Thu, 14 Apr 2022 10:31:25 GMT SKIPPED [3] test/with_dummyserver/test_socketlevel.py:2022: urllib3 uses Content-Length in this case
Thu, 14 Apr 2022 10:31:25 GMT ========= 1628 passed, 539 skipped, 446 warnings in 180.65s (0:03:00) ==========
Thu, 14 Apr 2022 10:31:25 GMT nox > Session test-3.11 was successful.
```

</details>

<details>
<summary>On April 20th, 3.11-dev timed out after 19m20s and times out ever since around 90%: <a href="https://github.com/urllib3/urllib3/runs/6097538739?check_suite_focus=true">https://github.com/urllib3/urllib3/runs/6097538739?check_suite_focus=true</a></summary>

```
Wed, 20 Apr 2022 15:10:39 GMT
Run ./ci/run_tests.sh
Wed, 20 Apr 2022 15:10:40 GMT nox > Running session test-3.11
Wed, 20 Apr 2022 15:10:40 GMT nox > Creating virtual environment (virtualenv) using python3.11 in .nox/test-3-11
Wed, 20 Apr 2022 15:10:40 GMT nox > python -m pip install -r dev-requirements.txt
Wed, 20 Apr 2022 15:11:07 GMT nox > python -m pip install '.[socks,secure,brotli]'
Wed, 20 Apr 2022 15:11:36 GMT nox > pip --version
Wed, 20 Apr 2022 15:11:36 GMT pip 22.0.4 from /home/runner/work/urllib3/urllib3/.nox/test-3-11/lib/python3.11/site-packages/pip (python 3.11)
Wed, 20 Apr 2022 15:11:36 GMT nox > python --version
Wed, 20 Apr 2022 15:11:36 GMT Python 3.11.0a7
Wed, 20 Apr 2022 15:11:36 GMT nox > python -c 'import struct; print(struct.calcsize('"'"'P'"'"') * 8)'
Wed, 20 Apr 2022 15:11:36 GMT 64
Wed, 20 Apr 2022 15:11:36 GMT nox > python -m OpenSSL.debug
Wed, 20 Apr 2022 15:11:36 GMT pyOpenSSL: 22.0.0
Wed, 20 Apr 2022 15:11:36 GMT cryptography: 35.0.0
Wed, 20 Apr 2022 15:11:36 GMT cffi: 1.15.0
Wed, 20 Apr 2022 15:11:36 GMT cryptography's compiled against OpenSSL: OpenSSL 1.1.1l  24 Aug 2021
Wed, 20 Apr 2022 15:11:36 GMT cryptography's linked OpenSSL: OpenSSL 1.1.1l  24 Aug 2021
Wed, 20 Apr 2022 15:11:36 GMT Python's OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
Wed, 20 Apr 2022 15:11:36 GMT Python executable: /home/runner/work/urllib3/urllib3/.nox/test-3-11/bin/python
Wed, 20 Apr 2022 15:11:36 GMT Python version: 3.11.0a7 (main, Apr 15 2022, 06:10:17) [GCC 9.4.0]
Wed, 20 Apr 2022 15:11:36 GMT Platform: linux
Wed, 20 Apr 2022 15:11:36 GMT sys.path: ['/home/runner/work/urllib3/urllib3', '/opt/hostedtoolcache/Python/3.11.0-alpha.7/x64/lib/python311.zip', '/opt/hostedtoolcache/Python/3.11.0-alpha.7/x64/lib/python3.11', '/opt/hostedtoolcache/Python/3.11.0-alpha.7/x64/lib/python3.11/lib-dynload', '/home/runner/work/urllib3/urllib3/.nox/test-3-11/lib/python3.11/site-packages']
Wed, 20 Apr 2022 15:11:36 GMT nox > python -bb -m coverage run --parallel-mode -m pytest -r a --color=yes --tb=native --no-success-flaky-report test/
Wed, 20 Apr 2022 15:11:37 GMT /home/runner/work/urllib3/urllib3/.nox/test-3-11/lib/python3.11/site-packages/pytest_freezegun.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
Wed, 20 Apr 2022 15:11:37 GMT   from distutils.version import LooseVersion
Wed, 20 Apr 2022 15:11:53 GMT ============================= test session starts ==============================
Wed, 20 Apr 2022 15:11:53 GMT platform linux -- Python 3.11.0a7, pytest-7.0.0, pluggy-1.0.0
Wed, 20 Apr 2022 15:11:53 GMT rootdir: /home/runner/work/urllib3/urllib3, configfile: setup.cfg
Wed, 20 Apr 2022 15:11:53 GMT plugins: timeout-2.1.0, flaky-3.7.0, freezegun-0.4.2
Wed, 20 Apr 2022 15:11:53 GMT collected 2168 items
Wed, 20 Apr 2022 15:11:53 GMT
Wed, 20 Apr 2022 15:11:53 GMT test/test_collections.py ......................................          [  1%]
Wed, 20 Apr 2022 15:11:53 GMT test/test_compatibility.py .                                             [  1%]
Wed, 20 Apr 2022 15:11:53 GMT test/test_connection.py ..................                               [  2%]
Wed, 20 Apr 2022 15:11:54 GMT test/test_connectionpool.py ............................................ [  4%]
Wed, 20 Apr 2022 15:11:54 GMT ...............................                                          [  6%]
Wed, 20 Apr 2022 15:11:54 GMT test/test_exceptions.py ..............                                   [  6%]
Wed, 20 Apr 2022 15:11:54 GMT test/test_fields.py ....................                                 [  7%]
Wed, 20 Apr 2022 15:11:54 GMT test/test_filepost.py .........                                          [  8%]
Wed, 20 Apr 2022 15:11:54 GMT test/test_no_ssl.py ..                                                   [  8%]
Wed, 20 Apr 2022 15:11:55 GMT test/test_poolmanager.py ..............................                  [  9%]
Wed, 20 Apr 2022 15:11:55 GMT test/test_proxymanager.py ......                                         [  9%]
Wed, 20 Apr 2022 15:11:55 GMT test/test_queue_monkeypatch.py .                                         [  9%]
Wed, 20 Apr 2022 15:11:55 GMT test/test_response.py .................................................. [ 12%]
Wed, 20 Apr 2022 15:11:55 GMT .....................                                                    [ 13%]
Wed, 20 Apr 2022 15:11:56 GMT test/test_retry.py ..................................................... [ 15%]
Wed, 20 Apr 2022 15:11:56 GMT .......                                                                  [ 15%]
Wed, 20 Apr 2022 15:11:58 GMT test/test_ssl.py ..........................................              [ 17%]
Wed, 20 Apr 2022 15:12:15 GMT test/test_ssltransport.py .................                              [ 18%]
Wed, 20 Apr 2022 15:12:39 GMT test/test_util.py ...................................................... [ 21%]
Wed, 20 Apr 2022 15:13:11 GMT ........................................................................ [ 24%]
Wed, 20 Apr 2022 15:13:45 GMT ........................................................................ [ 27%]
Wed, 20 Apr 2022 15:14:17 GMT ....................................s...s............................... [ 31%]
Wed, 20 Apr 2022 15:14:39 GMT .......................................................                  [ 33%]
Wed, 20 Apr 2022 15:15:11 GMT test/test_wait.py .............                                          [ 34%]
Wed, 20 Apr 2022 15:15:35 GMT test/contrib/test_pyopenssl.py ......................................... [ 36%]
Wed, 20 Apr 2022 15:16:14 GMT .........................ssssssssssssss.sssssssss.ssss.ssss.sssssssssss. [ 39%]
Wed, 20 Apr 2022 15:16:55 GMT s...ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 42%]
Wed, 20 Apr 2022 15:17:54 GMT ssssssssssssssssssssssssssss..........................................s. [ 46%]
Wed, 20 Apr 2022 15:19:03 GMT ........................................s.....s....s.................... [ 49%]
Wed, 20 Apr 2022 15:19:21 GMT ..............                                                           [ 50%]
Wed, 20 Apr 2022 15:19:22 GMT test/contrib/test_pyopenssl_dependencies.py ..                           [ 50%]
Wed, 20 Apr 2022 15:19:35 GMT test/contrib/test_securetransport.py sssssssssssssssssssssssssssssssssss [ 51%]
Wed, 20 Apr 2022 15:19:59 GMT ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 55%]
Wed, 20 Apr 2022 15:20:22 GMT ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 58%]
Wed, 20 Apr 2022 15:20:49 GMT sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss    [ 61%]
Wed, 20 Apr 2022 15:21:05 GMT test/contrib/test_socks.py ...................                           [ 62%]
Wed, 20 Apr 2022 15:21:18 GMT test/with_dummyserver/test_chunked_transfer.py .................         [ 63%]
Wed, 20 Apr 2022 15:21:41 GMT test/with_dummyserver/test_connectionpool.py ........................... [ 64%]
Wed, 20 Apr 2022 15:22:28 GMT ........................................................................ [ 67%]
Wed, 20 Apr 2022 15:23:16 GMT ........................................................................ [ 71%]
Wed, 20 Apr 2022 15:24:06 GMT ........................................................................ [ 74%]
Wed, 20 Apr 2022 15:24:54 GMT ........................................................................ [ 77%]
Wed, 20 Apr 2022 15:25:33 GMT .......................................                                  [ 79%]
Wed, 20 Apr 2022 15:25:55 GMT test/with_dummyserver/test_https.py ssssssssssssss.sssssssss.ssss.ssss.s [ 81%]
Wed, 20 Apr 2022 15:26:30 GMT ssssssssss.sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 84%]
Wed, 20 Apr 2022 15:27:20 GMT ssssssssssssssssssssssssssssssssssss.................................... [ 87%]
Wed, 20 Apr 2022 15:28:52 GMT ................................................s..........s............ [ 91%]
Wed, 20 Apr 2022 15:29:04 GMT ....                                                                     [ 91%]
Wed, 20 Apr 2022 15:29:06 GMT test/with_dummyserver/test_no_ssl.py ..                                  [ 91%]
Wed, 20 Apr 2022 15:29:28 GMT test/with_dummyserver/test_poolmanager.py .............................. [ 92%]
Wed, 20 Apr 2022 15:29:36 GMT .............                                                            [ 93%]
Wed, 20 Apr 2022 15:30:00 GMT Error: The operation was canceled.
```

</details>

The only difference I'm seeing is the switch from Python 3.11.0 alpha 6 to alpha 7. I initially thought that package installation would be taking much more time, but it's not the case. The bulk of the time is spent running tests as if alpha 7 had added a time.sleep() somewhere!

Should we bump the timeout to get full 3.11 runs?

**Comment by sethmlarson** [comment] 2022-06-01 18:44
Did a bit of work on this and it looks like I can reproduce the locking behavior with:

`$ nox -rs test-3.11 -- -vvv test/with_dummyserver/test_proxy_poolmanager.py::TestHTTPProxyManager --log-level=DEBUG --log-cli-level=10`

using the latest Python 3.11.0-beta3. Hangs on the test `test_cross_host_redirect` but when run alone the test doesn't hang. Looking at Wireshark captures it appears that the second request is sent but the Tornado server doesn't reply?

**Comment by sethmlarson** [comment] 2022-06-01 19:00
Currently running a `git bisect` on CPython with the following to see if I find any hints:

```
#!/bin/bash

set -exo pipefail

./configure
make
./python -m ensurepip
./python -m pip install ~/urllib3
./python -m pip install -r ~/urllib3/dev-requirements.txt
timeout 20 ./python -m pytest ~/urllib3/test/with_dummyserver/test_proxy_poolmanager.py::TestHTTPProxyManager
```

**Comment by pquentin** [comment] 2022-06-01 19:04
Thanks! To be clear what I've seen on CI was not hanging, just everything was slow. Bumping the timeout to 30mn would allow tests to finish I believe.

Your test hanging is interesting but probably a different issue?

**Comment by nateprewitt** [comment] 2022-06-01 19:07
I actually tried this last night funny enough, and 30 minutes does not fix the issue. It hangs on this test indefinitely and won't progress farther ([ref](https://github.com/nateprewitt/urllib3/runs/6684080658?check_suite_focus=true)).

**Comment by pquentin** [comment] 2022-06-02 02:47
Thanks, sorry for the confusion.

**Comment by sethmlarson** [comment] 2022-06-02 12:16
Closed in https://github.com/urllib3/urllib3/pull/2620

**Closed by sethmlarson** 2022-06-02 12:16 UTC

**Comment by pquentin** [comment] 2022-06-12 17:22
For what it's worth, what I was observing was real too, coverage is much slower on 3.11: https://github.com/nedbat/coveragepy/issues/1287
