### ISSUE TITLE
Encountering ssl.SSLCertVerificationError in attempting to retrieve a file from a website

### ISSUE THREAD

**Issue by OrbitalMechanic** [urllib3/urllib3#3033] opened 2023-05-17 04:20 UTC
### Subject

Describe the issue here.

I am running urllib3 to retrieve the file, SpaceWeather-v1.2.txt, from https://ftp.agi.com/pub/DynamicEarthData/. The result is the message and traceback as follows:

```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
```

Prior to May 17th, I have never had this problem.

### Environment

Running on a Mac Pro (2019) under Mac OSX ver. 13.1.1(a) Ventura under the Anaconda distribution.

```
Python\Anaconda version
-------------------------------------------------
Python 3.9.16 (main, Mar  8 2023, 04:29:44) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin

OS
-------------------------------------------------
OS macOS-10.16-x86_64-i386-64bit

Python version
-------------------------------------------------
Python 3.9.16

Version of urllib
-------------------------------------------------
urllib3 1.26.15
```

### Steps to Reproduce
Attached is a copy of the Python program used.
[plotting_sw_data_Rev-06.txt](https://github.com/urllib3/urllib3/files/11494121/plotting_sw_data_Rev-06.txt)

### Expected Behavior
What should happen.
Able to download the file through urllib3

### Actual Behavior
What happens instead.
See attached file.

[error_with_urllib.txt](https://github.com/urllib3/urllib3/files/11494099/error_with_urllib.txt)

**Comment by LoganB99** [comment] 2023-05-18 00:20
I think I have a similar issue
Using Python 3.10, urllib3 1.26.15, requests 2.28.1. I've tried several combinations 

https://github.com/psf/requests/issues/6443#issuecomment-1552218008

**Comment by thebigbird** [comment] 2023-05-18 13:27
I am having the same problem. 

`cademic import --bibtex export.bib
Traceback (most recent call last):
  File "/Users/dee4/Library/Python/3.8/bin/academic", line 5, in <module>
    from academic.cli import main
  File "/Users/dee4/Library/Python/3.9/lib/python/site-packages/academic/cli.py", line 12, in <module>
    from academic.import_assets import import_assets
  File "/Users/dee4/Library/Python/3.9/lib/python/site-packages/academic/import_assets.py", line 8, in <module>
    from requests import get
  File "/Users/dee4/Library/Python/3.9/lib/python/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/dee4/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py", line 38, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168
[TTS-220137ML:~] dee4% 
`

**Comment by sethmlarson** [comment] 2023-05-18 14:46
I don't think any of the three issues that have been mentioned above are related.

@OrbitalMechanic Since you didn't upgrade urllib3 it is highly unlikely that urllib3 is the cause of this error. Something changed either on your system (like your list of root certificates) or something changed on the website (they switched to a new certificate). Either way, we can't help you figure out what happened unfortunately.

@LoganB99 I don't know what to do with your error message, it appears cropped, but it also doesn't look like an issue with urllib3.

@thebigbird Read this part of the migration guide: https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#common-upgrading-issues

Closing this issue.

**Closed by sethmlarson** 2023-05-18 14:46 UTC
